// Code generated by ent, DO NOT EDIT.

package quotareleasereceipt

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the quotareleasereceipt type in the database.
	Label = "quota_release_receipt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldReceiptID holds the string denoting the receipt_id field in the database.
	FieldReceiptID = "receipt_id"
	// FieldOwnerService holds the string denoting the owner_service field in the database.
	FieldOwnerService = "owner_service"
	// FieldReleaseEventID holds the string denoting the release_event_id field in the database.
	FieldReleaseEventID = "release_event_id"
	// FieldPayloadHash holds the string denoting the payload_hash field in the database.
	FieldPayloadHash = "payload_hash"
	// FieldPayloadJSON holds the string denoting the payload_json field in the database.
	FieldPayloadJSON = "payload_json"
	// Table holds the table name of the quotareleasereceipt in the database.
	Table = "sys_quota_release_receipts"
)

// Columns holds all SQL columns for quotareleasereceipt fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldTenantID,
	FieldReceiptID,
	FieldOwnerService,
	FieldReleaseEventID,
	FieldPayloadHash,
	FieldPayloadJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-admin/app/admin/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// ReceiptIDValidator is a validator for the "receipt_id" field. It is called by the builders before save.
	ReceiptIDValidator func(string) error
	// OwnerServiceValidator is a validator for the "owner_service" field. It is called by the builders before save.
	OwnerServiceValidator func(string) error
	// ReleaseEventIDValidator is a validator for the "release_event_id" field. It is called by the builders before save.
	ReleaseEventIDValidator func(string) error
	// PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	PayloadHashValidator func(string) error
	// PayloadJSONValidator is a validator for the "payload_json" field. It is called by the builders before save.
	PayloadJSONValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the QuotaReleaseReceipt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByReceiptID orders the results by the receipt_id field.
func ByReceiptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiptID, opts...).ToFunc()
}

// ByOwnerService orders the results by the owner_service field.
func ByOwnerService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerService, opts...).ToFunc()
}

// ByReleaseEventID orders the results by the release_event_id field.
func ByReleaseEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseEventID, opts...).ToFunc()
}

// ByPayloadHash orders the results by the payload_hash field.
func ByPayloadHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadHash, opts...).ToFunc()
}

// ByPayloadJSON orders the results by the payload_json field.
func ByPayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadJSON, opts...).ToFunc()
}
