-- Access key creation idempotency record, generated from the
-- AccessKeyIdempotency Ent schema and the declarative schema exporter.
-- Deliberately a standalone relation with no foreign key to sys_access_keys:
-- sys_access_keys rows are physically deleted, and the record must outlive the
-- key so that create -> delete -> replay is still judged as a replay.
CREATE TABLE "public"."sys_access_key_idempotency" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "actor_id" bigint NOT NULL,
  "action" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "request_fingerprint" character varying NOT NULL,
  "access_key_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sys_access_key_idempotency_action_ck"
    CHECK (action = 'access_key.create'),
  CONSTRAINT "sys_access_key_idempotency_actor_positive_ck"
    CHECK (actor_id > 0),
  CONSTRAINT "sys_access_key_idempotency_tenant_positive_ck"
    CHECK (tenant_id > 0)
);
CREATE UNIQUE INDEX "uix_sys_access_key_idempotency_key"
  ON "public"."sys_access_key_idempotency" ("tenant_id", "actor_id", "action", "idempotency_key");
COMMENT ON TABLE "public"."sys_access_key_idempotency" IS '访问凭证创建幂等记录表';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."tenant_id" IS '租户ID';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."actor_id" IS '操作人用户ID';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."action" IS '操作标识（固定 access_key.create）';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."idempotency_key" IS '客户端提供的幂等键';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."request_fingerprint" IS '规范意图的 sha256 十六进制';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."access_key_id" IS '指向 sys_access_keys.id（回放原始对象）';
COMMENT ON COLUMN "public"."sys_access_key_idempotency"."created_at" IS '创建时间';
