-- CPU-P01 admission from the ModelDevAcceptance Ent schema and schema exporter.
-- Limited to the new CPU admission relation and its indexes. The Atlas diff's
-- pre-existing avatar/files removals and GPU check rewrite are outside this change.
CREATE TABLE "public"."sys_modeldev_acceptances" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "resource_tenant_id" character varying NOT NULL,
  "actor" character varying NOT NULL,
  "action" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "operation_id" character varying NOT NULL,
  "execution_id" character varying NOT NULL,
  "intent_hash" character varying NOT NULL,
  "intent_canonical" bytea NOT NULL,
  "execution_spec_hash" character varying NOT NULL,
  "snapshot_canonical" bytea NOT NULL,
  "accepted_at" timestamptz NOT NULL,
  "dispatch_state" character varying NOT NULL DEFAULT 'QUEUED',
  PRIMARY KEY ("id"),
  CONSTRAINT "sys_modeldev_acceptances_tenant_resource_mapping_fkey"
    FOREIGN KEY ("tenant_id", "resource_tenant_id")
    REFERENCES "public"."sys_tenants" ("id", "resource_tenant_id")
    ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT "sys_modeldev_acceptances_action_ck"
    CHECK (action = 'modeldev.execution.create'),
  CONSTRAINT "sys_modeldev_acceptances_tenant_positive_ck"
    CHECK (tenant_id > 0)
);
CREATE UNIQUE INDEX "sys_modeldev_acceptances_execution_id_key"
  ON "public"."sys_modeldev_acceptances" ("execution_id");
CREATE UNIQUE INDEX "sys_modeldev_acceptances_operation_id_key"
  ON "public"."sys_modeldev_acceptances" ("operation_id");
CREATE UNIQUE INDEX "uix_sys_modeldev_acceptances_idempotency"
  ON "public"."sys_modeldev_acceptances" ("resource_tenant_id", "actor", "action", "idempotency_key");
CREATE UNIQUE INDEX "uix_sys_modeldev_acceptances_tenant_execution"
  ON "public"."sys_modeldev_acceptances" ("tenant_id", "execution_id");
CREATE UNIQUE INDEX "uix_sys_modeldev_acceptances_tenant_operation"
  ON "public"."sys_modeldev_acceptances" ("tenant_id", "operation_id");
