-- QUOTA-GPU-LOCAL-01 expand：目录/账本表、新 nullable quota_code、必要索引。
-- 本迁移不对旧套餐数据加非空/唯一约束；回填与约束分别由
-- sql/quota/001_catalog_and_backfill.sql 与 20260922190100_quota_constraints.sql 完成。
-- 与 schema.sql 的已知偏差（本批有意为之，见 evidence/migration-report.md）：
--   * 新账本表额外的 CHECK 约束（tenant_id>0、occupied>=0、0<=released<=original）；
--   * 这些检查 Ent 导出器暂不支持，未来 migrate diff 会列为 DROP 候选，须逐行审查保留。

-- ── 配额目录 ──────────────────────────────────────────────
CREATE TABLE "sys_quota_definitions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NULL,
  "code" character varying NOT NULL,
  "display_name" character varying NOT NULL,
  "unit" character varying NOT NULL,
  "accounting_kind" character varying NOT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "sys_quota_definitions_code_key" ON "sys_quota_definitions" ("code");
CREATE INDEX "quotadefinition_created_at" ON "sys_quota_definitions" ("created_at");
COMMENT ON TABLE "sys_quota_definitions" IS '配额目录表';
COMMENT ON COLUMN "sys_quota_definitions"."code" IS '稳定配额编码（如 gpu.count）';
COMMENT ON COLUMN "sys_quota_definitions"."unit" IS '单位（user/byte/request/gpu）';

-- ── 租户配额账户 ──────────────────────────────────────────
CREATE TABLE "sys_quota_accounts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  "tenant_id" bigint NULL DEFAULT 0,
  "quota_code" character varying NOT NULL,
  "occupied_units" bigint NOT NULL DEFAULT 0,
  "version" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "sys_quota_accounts_tenant_fkey" FOREIGN KEY ("tenant_id") REFERENCES "sys_tenants" ("id") ON DELETE RESTRICT,
  CONSTRAINT "sys_quota_accounts_tenant_positive_ck" CHECK ("tenant_id" > 0),
  CONSTRAINT "sys_quota_accounts_occupied_nonnegative_ck" CHECK ("occupied_units" >= 0)
);
CREATE UNIQUE INDEX "uix_sys_quota_accounts_tenant_id_quota_code" ON "sys_quota_accounts" ("tenant_id", "quota_code");
COMMENT ON TABLE "sys_quota_accounts" IS '租户配额账户表';
COMMENT ON COLUMN "sys_quota_accounts"."occupied_units" IS '当前占用数量';
COMMENT ON COLUMN "sys_quota_accounts"."version" IS '版本号';

-- ── 配额操作与持久化转发记录 ──────────────────────────────
CREATE TABLE "sys_quota_operations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  "tenant_id" bigint NULL DEFAULT 0,
  "operation_id" character varying NOT NULL,
  "resource_tenant_id" character varying NOT NULL,
  "resource_id" character varying NOT NULL,
  "create_operation_id" character varying NULL,
  "actor_type" character varying NOT NULL,
  "actor_id" character varying NOT NULL,
  "owner_service" character varying NOT NULL,
  "action" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "request_hash" character varying NOT NULL,
  "canonical_request" text NOT NULL,
  "dispatch_state" character varying NOT NULL DEFAULT 'QUEUED',
  "attempt_count" bigint NOT NULL DEFAULT 0,
  "lease_generation" bigint NOT NULL DEFAULT 0,
  "retry_blocked" boolean NOT NULL DEFAULT false,
  "last_error_code" character varying NULL,
  "next_attempt_at" timestamptz NULL,
  "lease_owner" character varying NULL,
  "lease_until" timestamptz NULL,
  "ack_json" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sys_quota_operations_tenant_fkey" FOREIGN KEY ("tenant_id") REFERENCES "sys_tenants" ("id") ON DELETE RESTRICT,
  CONSTRAINT "sys_quota_operations_tenant_positive_ck" CHECK ("tenant_id" > 0)
);
CREATE UNIQUE INDEX "sys_quota_operations_operation_id_key" ON "sys_quota_operations" ("operation_id");
CREATE UNIQUE INDEX "uix_sys_quota_operations_tenant_id_operation_id" ON "sys_quota_operations" ("tenant_id", "operation_id");
CREATE UNIQUE INDEX "uix_sys_quota_operations_idempotency" ON "sys_quota_operations" ("tenant_id", "actor_type", "actor_id", "action", "idempotency_key");
CREATE INDEX "idx_sys_quota_operations_dispatch" ON "sys_quota_operations" ("dispatch_state", "next_attempt_at");
CREATE UNIQUE INDEX "uix_sys_quota_operations_create_resource" ON "sys_quota_operations" ("tenant_id", "owner_service", "resource_id") WHERE create_operation_id IS NULL;
-- 自引用复合 FK 需要被引用的 (tenant_id, operation_id) 唯一索引先存在，
-- 故在索引创建之后以 ALTER 添加。
ALTER TABLE "sys_quota_operations" ADD CONSTRAINT "sys_quota_operations_create_operation_fkey" FOREIGN KEY ("tenant_id", "create_operation_id") REFERENCES "sys_quota_operations" ("tenant_id", "operation_id") ON DELETE RESTRICT;
COMMENT ON TABLE "sys_quota_operations" IS '配额操作与持久化转发记录表';

-- ── 占额明细 ──────────────────────────────────────────────
CREATE TABLE "sys_quota_charges" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  "tenant_id" bigint NULL DEFAULT 0,
  "charge_id" character varying NOT NULL,
  "operation_id" character varying NOT NULL,
  "quota_code" character varying NOT NULL,
  "original_units" bigint NOT NULL,
  "released_units" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "sys_quota_charges_tenant_fkey" FOREIGN KEY ("tenant_id") REFERENCES "sys_tenants" ("id") ON DELETE RESTRICT,
  CONSTRAINT "sys_quota_charges_tenant_positive_ck" CHECK ("tenant_id" > 0),
  CONSTRAINT "sys_quota_charges_tenant_operation_fkey" FOREIGN KEY ("tenant_id", "operation_id") REFERENCES "sys_quota_operations" ("tenant_id", "operation_id") ON DELETE RESTRICT,
  CONSTRAINT "sys_quota_charges_tenant_account_fkey" FOREIGN KEY ("tenant_id", "quota_code") REFERENCES "sys_quota_accounts" ("tenant_id", "quota_code") ON DELETE RESTRICT,
  CONSTRAINT "sys_quota_charges_release_range_ck" CHECK ("released_units" >= 0 AND "released_units" <= "original_units"),
  CONSTRAINT "sys_quota_charges_original_positive_ck" CHECK ("original_units" >= 0)
);
CREATE UNIQUE INDEX "sys_quota_charges_charge_id_key" ON "sys_quota_charges" ("charge_id");
CREATE UNIQUE INDEX "uix_sys_quota_charges_tenant_id_charge_id" ON "sys_quota_charges" ("tenant_id", "charge_id");
CREATE UNIQUE INDEX "uix_sys_quota_charges_tenant_operation_code" ON "sys_quota_charges" ("tenant_id", "operation_id", "quota_code");
CREATE INDEX "idx_sys_quota_charges_quota_code" ON "sys_quota_charges" ("quota_code");
COMMENT ON TABLE "sys_quota_charges" IS '配额占额明细表';

-- ── 退额回执 ──────────────────────────────────────────────
CREATE TABLE "sys_quota_release_receipts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NULL,
  "tenant_id" bigint NULL DEFAULT 0,
  "receipt_id" character varying NOT NULL,
  "owner_service" character varying NOT NULL,
  "release_event_id" character varying NOT NULL,
  "payload_hash" character varying NOT NULL,
  "payload_json" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sys_quota_release_receipts_tenant_fkey" FOREIGN KEY ("tenant_id") REFERENCES "sys_tenants" ("id") ON DELETE RESTRICT,
  CONSTRAINT "sys_quota_release_receipts_tenant_positive_ck" CHECK ("tenant_id" > 0)
);
CREATE UNIQUE INDEX "sys_quota_release_receipts_receipt_id_key" ON "sys_quota_release_receipts" ("receipt_id");
CREATE UNIQUE INDEX "uix_sys_quota_release_receipts_owner_event" ON "sys_quota_release_receipts" ("owner_service", "release_event_id");
COMMENT ON TABLE "sys_quota_release_receipts" IS '配额退额回执表';

-- ── 旧套餐配额表：新增 nullable quota_code（暂不加非空/唯一/FK） ──
ALTER TABLE "sys_plan_quotas" ADD COLUMN "quota_code" character varying NULL;
COMMENT ON COLUMN "sys_plan_quotas"."quota_code" IS '配额编码';
