// Code generated by ent, DO NOT EDIT.

package membershipposition

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldTenantID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldRemark, v))
}

// MembershipID applies equality check predicate on the "membership_id" field. It's identical to MembershipIDEQ.
func MembershipID(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldMembershipID, v))
}

// PositionID applies equality check predicate on the "position_id" field. It's identical to PositionIDEQ.
func PositionID(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldPositionID, v))
}

// IsPrimary applies equality check predicate on the "is_primary" field. It's identical to IsPrimaryEQ.
func IsPrimary(v bool) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldIsPrimary, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldStartAt, v))
}

// EndAt applies equality check predicate on the "end_at" field. It's identical to EndAtEQ.
func EndAt(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldEndAt, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedBy applies equality check predicate on the "assigned_by" field. It's identical to AssignedByEQ.
func AssignedBy(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldAssignedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldTenantID))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldContainsFold(FieldRemark, v))
}

// MembershipIDEQ applies the EQ predicate on the "membership_id" field.
func MembershipIDEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldMembershipID, v))
}

// MembershipIDNEQ applies the NEQ predicate on the "membership_id" field.
func MembershipIDNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldMembershipID, v))
}

// MembershipIDIn applies the In predicate on the "membership_id" field.
func MembershipIDIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldMembershipID, vs...))
}

// MembershipIDNotIn applies the NotIn predicate on the "membership_id" field.
func MembershipIDNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldMembershipID, vs...))
}

// MembershipIDGT applies the GT predicate on the "membership_id" field.
func MembershipIDGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldMembershipID, v))
}

// MembershipIDGTE applies the GTE predicate on the "membership_id" field.
func MembershipIDGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldMembershipID, v))
}

// MembershipIDLT applies the LT predicate on the "membership_id" field.
func MembershipIDLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldMembershipID, v))
}

// MembershipIDLTE applies the LTE predicate on the "membership_id" field.
func MembershipIDLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldMembershipID, v))
}

// PositionIDEQ applies the EQ predicate on the "position_id" field.
func PositionIDEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldPositionID, v))
}

// PositionIDNEQ applies the NEQ predicate on the "position_id" field.
func PositionIDNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldPositionID, v))
}

// PositionIDIn applies the In predicate on the "position_id" field.
func PositionIDIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldPositionID, vs...))
}

// PositionIDNotIn applies the NotIn predicate on the "position_id" field.
func PositionIDNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldPositionID, vs...))
}

// PositionIDGT applies the GT predicate on the "position_id" field.
func PositionIDGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldPositionID, v))
}

// PositionIDGTE applies the GTE predicate on the "position_id" field.
func PositionIDGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldPositionID, v))
}

// PositionIDLT applies the LT predicate on the "position_id" field.
func PositionIDLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldPositionID, v))
}

// PositionIDLTE applies the LTE predicate on the "position_id" field.
func PositionIDLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldPositionID, v))
}

// IsPrimaryEQ applies the EQ predicate on the "is_primary" field.
func IsPrimaryEQ(v bool) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldIsPrimary, v))
}

// IsPrimaryNEQ applies the NEQ predicate on the "is_primary" field.
func IsPrimaryNEQ(v bool) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldIsPrimary, v))
}

// IsPrimaryIsNil applies the IsNil predicate on the "is_primary" field.
func IsPrimaryIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldIsPrimary))
}

// IsPrimaryNotNil applies the NotNil predicate on the "is_primary" field.
func IsPrimaryNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldIsPrimary))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldStartAt, v))
}

// StartAtIsNil applies the IsNil predicate on the "start_at" field.
func StartAtIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldStartAt))
}

// StartAtNotNil applies the NotNil predicate on the "start_at" field.
func StartAtNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldStartAt))
}

// EndAtEQ applies the EQ predicate on the "end_at" field.
func EndAtEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldEndAt, v))
}

// EndAtNEQ applies the NEQ predicate on the "end_at" field.
func EndAtNEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldEndAt, v))
}

// EndAtIn applies the In predicate on the "end_at" field.
func EndAtIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldEndAt, vs...))
}

// EndAtNotIn applies the NotIn predicate on the "end_at" field.
func EndAtNotIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldEndAt, vs...))
}

// EndAtGT applies the GT predicate on the "end_at" field.
func EndAtGT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldEndAt, v))
}

// EndAtGTE applies the GTE predicate on the "end_at" field.
func EndAtGTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldEndAt, v))
}

// EndAtLT applies the LT predicate on the "end_at" field.
func EndAtLT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldEndAt, v))
}

// EndAtLTE applies the LTE predicate on the "end_at" field.
func EndAtLTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldEndAt, v))
}

// EndAtIsNil applies the IsNil predicate on the "end_at" field.
func EndAtIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldEndAt))
}

// EndAtNotNil applies the NotNil predicate on the "end_at" field.
func EndAtNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldEndAt))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldAssignedAt, v))
}

// AssignedAtIsNil applies the IsNil predicate on the "assigned_at" field.
func AssignedAtIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldAssignedAt))
}

// AssignedAtNotNil applies the NotNil predicate on the "assigned_at" field.
func AssignedAtNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldAssignedAt))
}

// AssignedByEQ applies the EQ predicate on the "assigned_by" field.
func AssignedByEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldAssignedBy, v))
}

// AssignedByNEQ applies the NEQ predicate on the "assigned_by" field.
func AssignedByNEQ(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldAssignedBy, v))
}

// AssignedByIn applies the In predicate on the "assigned_by" field.
func AssignedByIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldAssignedBy, vs...))
}

// AssignedByNotIn applies the NotIn predicate on the "assigned_by" field.
func AssignedByNotIn(vs ...uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldAssignedBy, vs...))
}

// AssignedByGT applies the GT predicate on the "assigned_by" field.
func AssignedByGT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGT(FieldAssignedBy, v))
}

// AssignedByGTE applies the GTE predicate on the "assigned_by" field.
func AssignedByGTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldGTE(FieldAssignedBy, v))
}

// AssignedByLT applies the LT predicate on the "assigned_by" field.
func AssignedByLT(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLT(FieldAssignedBy, v))
}

// AssignedByLTE applies the LTE predicate on the "assigned_by" field.
func AssignedByLTE(v uint32) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldLTE(FieldAssignedBy, v))
}

// AssignedByIsNil applies the IsNil predicate on the "assigned_by" field.
func AssignedByIsNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIsNull(FieldAssignedBy))
}

// AssignedByNotNil applies the NotNil predicate on the "assigned_by" field.
func AssignedByNotNil() predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotNull(FieldAssignedBy))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.FieldNotIn(FieldStatus, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MembershipPosition) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MembershipPosition) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MembershipPosition) predicate.MembershipPosition {
	return predicate.MembershipPosition(sql.NotPredicates(p))
}
