-- Isolated acceptance only. Run explicitly by the task container administrator.
CREATE ROLE gov_acc_migrate LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE gov_acc_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE DATABASE gov_acc_data OWNER gov_acc_migrate;
CREATE DATABASE gov_acc_dev OWNER gov_acc_migrate;
REVOKE ALL ON DATABASE gov_acc_data FROM PUBLIC;
GRANT CONNECT ON DATABASE gov_acc_data TO gov_acc_runtime;
CREATE ROLE gov_acc_joint_b_migrate LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE gov_acc_joint_b_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE DATABASE gov_acc_joint_b OWNER gov_acc_joint_b_migrate;
REVOKE ALL ON DATABASE gov_acc_joint_b FROM PUBLIC;
GRANT CONNECT ON DATABASE gov_acc_joint_b TO gov_acc_joint_b_runtime;
CREATE ROLE gov_acc_owner_migrate LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE gov_acc_owner_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE DATABASE gov_acc_test_owner OWNER gov_acc_owner_migrate;
REVOKE ALL ON DATABASE gov_acc_test_owner FROM PUBLIC;
GRANT CONNECT ON DATABASE gov_acc_test_owner TO gov_acc_owner_runtime;
