syntax = "proto3";

package admin.service.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

import "pagination/v1/pagination.proto";
import "identity/service/v1/plan_module.proto";

// 套餐模块白名单管理服务
service PlanModuleService {
  // 分页查询套餐模块列表
  rpc List (pagination.PagingRequest) returns (identity.service.v1.ListPlanModuleResponse) {
    option (google.api.http) = {
      get: "/admin/v1/plan-modules"
    };
  }

  // 查询套餐模块详情
  rpc Get (identity.service.v1.GetPlanModuleRequest) returns (identity.service.v1.PlanModule) {
    option (google.api.http) = {
      get: "/admin/v1/plan-modules/{id}"
    };
  }

  // 创建套餐模块
  rpc Create (identity.service.v1.CreatePlanModuleRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/admin/v1/plan-modules"
      body: "*"
    };
  }

  // 更新套餐模块
  rpc Update (identity.service.v1.UpdatePlanModuleRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/admin/v1/plan-modules/{id}"
      body: "*"
    };
  }

  // 删除套餐模块
  rpc Delete (identity.service.v1.DeletePlanModuleRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/admin/v1/plan-modules"
    };
  }
}
