// Code generated by ent, DO NOT EDIT.

package modeldevacceptance

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldTenantID, v))
}

// ResourceTenantID applies equality check predicate on the "resource_tenant_id" field. It's identical to ResourceTenantIDEQ.
func ResourceTenantID(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldResourceTenantID, v))
}

// Actor applies equality check predicate on the "actor" field. It's identical to ActorEQ.
func Actor(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldActor, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldAction, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldIdempotencyKey, v))
}

// OperationID applies equality check predicate on the "operation_id" field. It's identical to OperationIDEQ.
func OperationID(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldOperationID, v))
}

// ExecutionID applies equality check predicate on the "execution_id" field. It's identical to ExecutionIDEQ.
func ExecutionID(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldExecutionID, v))
}

// IntentHash applies equality check predicate on the "intent_hash" field. It's identical to IntentHashEQ.
func IntentHash(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldIntentHash, v))
}

// IntentCanonical applies equality check predicate on the "intent_canonical" field. It's identical to IntentCanonicalEQ.
func IntentCanonical(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldIntentCanonical, v))
}

// ExecutionSpecHash applies equality check predicate on the "execution_spec_hash" field. It's identical to ExecutionSpecHashEQ.
func ExecutionSpecHash(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldExecutionSpecHash, v))
}

// SnapshotCanonical applies equality check predicate on the "snapshot_canonical" field. It's identical to SnapshotCanonicalEQ.
func SnapshotCanonical(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldSnapshotCanonical, v))
}

// AcceptedAt applies equality check predicate on the "accepted_at" field. It's identical to AcceptedAtEQ.
func AcceptedAt(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldAcceptedAt, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldAttemptCount, v))
}

// LeaseGeneration applies equality check predicate on the "lease_generation" field. It's identical to LeaseGenerationEQ.
func LeaseGeneration(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLeaseGeneration, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseUntil applies equality check predicate on the "lease_until" field. It's identical to LeaseUntilEQ.
func LeaseUntil(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLeaseUntil, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldNextAttemptAt, v))
}

// RetryBlocked applies equality check predicate on the "retry_blocked" field. It's identical to RetryBlockedEQ.
func RetryBlocked(v bool) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldRetryBlocked, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLastErrorCode, v))
}

// OwnerReceiptCanonical applies equality check predicate on the "owner_receipt_canonical" field. It's identical to OwnerReceiptCanonicalEQ.
func OwnerReceiptCanonical(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldOwnerReceiptCanonical, v))
}

// StopIntentGeneration applies equality check predicate on the "stop_intent_generation" field. It's identical to StopIntentGenerationEQ.
func StopIntentGeneration(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldStopIntentGeneration, v))
}

// StopRequestedAt applies equality check predicate on the "stop_requested_at" field. It's identical to StopRequestedAtEQ.
func StopRequestedAt(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldStopRequestedAt, v))
}

// StopRequestedActor applies equality check predicate on the "stop_requested_actor" field. It's identical to StopRequestedActorEQ.
func StopRequestedActor(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldStopRequestedActor, v))
}

// CloseAttemptCount applies equality check predicate on the "close_attempt_count" field. It's identical to CloseAttemptCountEQ.
func CloseAttemptCount(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseAttemptCount, v))
}

// CloseLeaseGeneration applies equality check predicate on the "close_lease_generation" field. It's identical to CloseLeaseGenerationEQ.
func CloseLeaseGeneration(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLeaseGeneration, v))
}

// CloseLeaseOwner applies equality check predicate on the "close_lease_owner" field. It's identical to CloseLeaseOwnerEQ.
func CloseLeaseOwner(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLeaseOwner, v))
}

// CloseLeaseUntil applies equality check predicate on the "close_lease_until" field. It's identical to CloseLeaseUntilEQ.
func CloseLeaseUntil(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLeaseUntil, v))
}

// CloseNextAttemptAt applies equality check predicate on the "close_next_attempt_at" field. It's identical to CloseNextAttemptAtEQ.
func CloseNextAttemptAt(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseNextAttemptAt, v))
}

// CloseRetryBlocked applies equality check predicate on the "close_retry_blocked" field. It's identical to CloseRetryBlockedEQ.
func CloseRetryBlocked(v bool) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseRetryBlocked, v))
}

// CloseLastErrorCode applies equality check predicate on the "close_last_error_code" field. It's identical to CloseLastErrorCodeEQ.
func CloseLastErrorCode(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLastErrorCode, v))
}

// CloseReceiptCanonical applies equality check predicate on the "close_receipt_canonical" field. It's identical to CloseReceiptCanonicalEQ.
func CloseReceiptCanonical(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseReceiptCanonical, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldTenantID, v))
}

// ResourceTenantIDEQ applies the EQ predicate on the "resource_tenant_id" field.
func ResourceTenantIDEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldResourceTenantID, v))
}

// ResourceTenantIDNEQ applies the NEQ predicate on the "resource_tenant_id" field.
func ResourceTenantIDNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldResourceTenantID, v))
}

// ResourceTenantIDIn applies the In predicate on the "resource_tenant_id" field.
func ResourceTenantIDIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldResourceTenantID, vs...))
}

// ResourceTenantIDNotIn applies the NotIn predicate on the "resource_tenant_id" field.
func ResourceTenantIDNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldResourceTenantID, vs...))
}

// ResourceTenantIDGT applies the GT predicate on the "resource_tenant_id" field.
func ResourceTenantIDGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldResourceTenantID, v))
}

// ResourceTenantIDGTE applies the GTE predicate on the "resource_tenant_id" field.
func ResourceTenantIDGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldResourceTenantID, v))
}

// ResourceTenantIDLT applies the LT predicate on the "resource_tenant_id" field.
func ResourceTenantIDLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldResourceTenantID, v))
}

// ResourceTenantIDLTE applies the LTE predicate on the "resource_tenant_id" field.
func ResourceTenantIDLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldResourceTenantID, v))
}

// ResourceTenantIDContains applies the Contains predicate on the "resource_tenant_id" field.
func ResourceTenantIDContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldResourceTenantID, v))
}

// ResourceTenantIDHasPrefix applies the HasPrefix predicate on the "resource_tenant_id" field.
func ResourceTenantIDHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldResourceTenantID, v))
}

// ResourceTenantIDHasSuffix applies the HasSuffix predicate on the "resource_tenant_id" field.
func ResourceTenantIDHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldResourceTenantID, v))
}

// ResourceTenantIDEqualFold applies the EqualFold predicate on the "resource_tenant_id" field.
func ResourceTenantIDEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldResourceTenantID, v))
}

// ResourceTenantIDContainsFold applies the ContainsFold predicate on the "resource_tenant_id" field.
func ResourceTenantIDContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldResourceTenantID, v))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldActor, vs...))
}

// ActorGT applies the GT predicate on the "actor" field.
func ActorGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldActor, v))
}

// ActorGTE applies the GTE predicate on the "actor" field.
func ActorGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldActor, v))
}

// ActorLT applies the LT predicate on the "actor" field.
func ActorLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldActor, v))
}

// ActorLTE applies the LTE predicate on the "actor" field.
func ActorLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldActor, v))
}

// ActorContains applies the Contains predicate on the "actor" field.
func ActorContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldActor, v))
}

// ActorHasPrefix applies the HasPrefix predicate on the "actor" field.
func ActorHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldActor, v))
}

// ActorHasSuffix applies the HasSuffix predicate on the "actor" field.
func ActorHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldActor, v))
}

// ActorEqualFold applies the EqualFold predicate on the "actor" field.
func ActorEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldActor, v))
}

// ActorContainsFold applies the ContainsFold predicate on the "actor" field.
func ActorContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldActor, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldAction, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// OperationIDEQ applies the EQ predicate on the "operation_id" field.
func OperationIDEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldOperationID, v))
}

// OperationIDNEQ applies the NEQ predicate on the "operation_id" field.
func OperationIDNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldOperationID, v))
}

// OperationIDIn applies the In predicate on the "operation_id" field.
func OperationIDIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldOperationID, vs...))
}

// OperationIDNotIn applies the NotIn predicate on the "operation_id" field.
func OperationIDNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldOperationID, vs...))
}

// OperationIDGT applies the GT predicate on the "operation_id" field.
func OperationIDGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldOperationID, v))
}

// OperationIDGTE applies the GTE predicate on the "operation_id" field.
func OperationIDGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldOperationID, v))
}

// OperationIDLT applies the LT predicate on the "operation_id" field.
func OperationIDLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldOperationID, v))
}

// OperationIDLTE applies the LTE predicate on the "operation_id" field.
func OperationIDLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldOperationID, v))
}

// OperationIDContains applies the Contains predicate on the "operation_id" field.
func OperationIDContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldOperationID, v))
}

// OperationIDHasPrefix applies the HasPrefix predicate on the "operation_id" field.
func OperationIDHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldOperationID, v))
}

// OperationIDHasSuffix applies the HasSuffix predicate on the "operation_id" field.
func OperationIDHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldOperationID, v))
}

// OperationIDEqualFold applies the EqualFold predicate on the "operation_id" field.
func OperationIDEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldOperationID, v))
}

// OperationIDContainsFold applies the ContainsFold predicate on the "operation_id" field.
func OperationIDContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldOperationID, v))
}

// ExecutionIDEQ applies the EQ predicate on the "execution_id" field.
func ExecutionIDEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldExecutionID, v))
}

// ExecutionIDNEQ applies the NEQ predicate on the "execution_id" field.
func ExecutionIDNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldExecutionID, v))
}

// ExecutionIDIn applies the In predicate on the "execution_id" field.
func ExecutionIDIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldExecutionID, vs...))
}

// ExecutionIDNotIn applies the NotIn predicate on the "execution_id" field.
func ExecutionIDNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldExecutionID, vs...))
}

// ExecutionIDGT applies the GT predicate on the "execution_id" field.
func ExecutionIDGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldExecutionID, v))
}

// ExecutionIDGTE applies the GTE predicate on the "execution_id" field.
func ExecutionIDGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldExecutionID, v))
}

// ExecutionIDLT applies the LT predicate on the "execution_id" field.
func ExecutionIDLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldExecutionID, v))
}

// ExecutionIDLTE applies the LTE predicate on the "execution_id" field.
func ExecutionIDLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldExecutionID, v))
}

// ExecutionIDContains applies the Contains predicate on the "execution_id" field.
func ExecutionIDContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldExecutionID, v))
}

// ExecutionIDHasPrefix applies the HasPrefix predicate on the "execution_id" field.
func ExecutionIDHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldExecutionID, v))
}

// ExecutionIDHasSuffix applies the HasSuffix predicate on the "execution_id" field.
func ExecutionIDHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldExecutionID, v))
}

// ExecutionIDEqualFold applies the EqualFold predicate on the "execution_id" field.
func ExecutionIDEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldExecutionID, v))
}

// ExecutionIDContainsFold applies the ContainsFold predicate on the "execution_id" field.
func ExecutionIDContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldExecutionID, v))
}

// IntentHashEQ applies the EQ predicate on the "intent_hash" field.
func IntentHashEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldIntentHash, v))
}

// IntentHashNEQ applies the NEQ predicate on the "intent_hash" field.
func IntentHashNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldIntentHash, v))
}

// IntentHashIn applies the In predicate on the "intent_hash" field.
func IntentHashIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldIntentHash, vs...))
}

// IntentHashNotIn applies the NotIn predicate on the "intent_hash" field.
func IntentHashNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldIntentHash, vs...))
}

// IntentHashGT applies the GT predicate on the "intent_hash" field.
func IntentHashGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldIntentHash, v))
}

// IntentHashGTE applies the GTE predicate on the "intent_hash" field.
func IntentHashGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldIntentHash, v))
}

// IntentHashLT applies the LT predicate on the "intent_hash" field.
func IntentHashLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldIntentHash, v))
}

// IntentHashLTE applies the LTE predicate on the "intent_hash" field.
func IntentHashLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldIntentHash, v))
}

// IntentHashContains applies the Contains predicate on the "intent_hash" field.
func IntentHashContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldIntentHash, v))
}

// IntentHashHasPrefix applies the HasPrefix predicate on the "intent_hash" field.
func IntentHashHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldIntentHash, v))
}

// IntentHashHasSuffix applies the HasSuffix predicate on the "intent_hash" field.
func IntentHashHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldIntentHash, v))
}

// IntentHashEqualFold applies the EqualFold predicate on the "intent_hash" field.
func IntentHashEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldIntentHash, v))
}

// IntentHashContainsFold applies the ContainsFold predicate on the "intent_hash" field.
func IntentHashContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldIntentHash, v))
}

// IntentCanonicalEQ applies the EQ predicate on the "intent_canonical" field.
func IntentCanonicalEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldIntentCanonical, v))
}

// IntentCanonicalNEQ applies the NEQ predicate on the "intent_canonical" field.
func IntentCanonicalNEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldIntentCanonical, v))
}

// IntentCanonicalIn applies the In predicate on the "intent_canonical" field.
func IntentCanonicalIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldIntentCanonical, vs...))
}

// IntentCanonicalNotIn applies the NotIn predicate on the "intent_canonical" field.
func IntentCanonicalNotIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldIntentCanonical, vs...))
}

// IntentCanonicalGT applies the GT predicate on the "intent_canonical" field.
func IntentCanonicalGT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldIntentCanonical, v))
}

// IntentCanonicalGTE applies the GTE predicate on the "intent_canonical" field.
func IntentCanonicalGTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldIntentCanonical, v))
}

// IntentCanonicalLT applies the LT predicate on the "intent_canonical" field.
func IntentCanonicalLT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldIntentCanonical, v))
}

// IntentCanonicalLTE applies the LTE predicate on the "intent_canonical" field.
func IntentCanonicalLTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldIntentCanonical, v))
}

// ExecutionSpecHashEQ applies the EQ predicate on the "execution_spec_hash" field.
func ExecutionSpecHashEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashNEQ applies the NEQ predicate on the "execution_spec_hash" field.
func ExecutionSpecHashNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashIn applies the In predicate on the "execution_spec_hash" field.
func ExecutionSpecHashIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldExecutionSpecHash, vs...))
}

// ExecutionSpecHashNotIn applies the NotIn predicate on the "execution_spec_hash" field.
func ExecutionSpecHashNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldExecutionSpecHash, vs...))
}

// ExecutionSpecHashGT applies the GT predicate on the "execution_spec_hash" field.
func ExecutionSpecHashGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashGTE applies the GTE predicate on the "execution_spec_hash" field.
func ExecutionSpecHashGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashLT applies the LT predicate on the "execution_spec_hash" field.
func ExecutionSpecHashLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashLTE applies the LTE predicate on the "execution_spec_hash" field.
func ExecutionSpecHashLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashContains applies the Contains predicate on the "execution_spec_hash" field.
func ExecutionSpecHashContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashHasPrefix applies the HasPrefix predicate on the "execution_spec_hash" field.
func ExecutionSpecHashHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashHasSuffix applies the HasSuffix predicate on the "execution_spec_hash" field.
func ExecutionSpecHashHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashEqualFold applies the EqualFold predicate on the "execution_spec_hash" field.
func ExecutionSpecHashEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldExecutionSpecHash, v))
}

// ExecutionSpecHashContainsFold applies the ContainsFold predicate on the "execution_spec_hash" field.
func ExecutionSpecHashContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldExecutionSpecHash, v))
}

// SnapshotCanonicalEQ applies the EQ predicate on the "snapshot_canonical" field.
func SnapshotCanonicalEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldSnapshotCanonical, v))
}

// SnapshotCanonicalNEQ applies the NEQ predicate on the "snapshot_canonical" field.
func SnapshotCanonicalNEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldSnapshotCanonical, v))
}

// SnapshotCanonicalIn applies the In predicate on the "snapshot_canonical" field.
func SnapshotCanonicalIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldSnapshotCanonical, vs...))
}

// SnapshotCanonicalNotIn applies the NotIn predicate on the "snapshot_canonical" field.
func SnapshotCanonicalNotIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldSnapshotCanonical, vs...))
}

// SnapshotCanonicalGT applies the GT predicate on the "snapshot_canonical" field.
func SnapshotCanonicalGT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldSnapshotCanonical, v))
}

// SnapshotCanonicalGTE applies the GTE predicate on the "snapshot_canonical" field.
func SnapshotCanonicalGTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldSnapshotCanonical, v))
}

// SnapshotCanonicalLT applies the LT predicate on the "snapshot_canonical" field.
func SnapshotCanonicalLT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldSnapshotCanonical, v))
}

// SnapshotCanonicalLTE applies the LTE predicate on the "snapshot_canonical" field.
func SnapshotCanonicalLTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldSnapshotCanonical, v))
}

// AcceptedAtEQ applies the EQ predicate on the "accepted_at" field.
func AcceptedAtEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedAtNEQ applies the NEQ predicate on the "accepted_at" field.
func AcceptedAtNEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldAcceptedAt, v))
}

// AcceptedAtIn applies the In predicate on the "accepted_at" field.
func AcceptedAtIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldAcceptedAt, vs...))
}

// AcceptedAtNotIn applies the NotIn predicate on the "accepted_at" field.
func AcceptedAtNotIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldAcceptedAt, vs...))
}

// AcceptedAtGT applies the GT predicate on the "accepted_at" field.
func AcceptedAtGT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldAcceptedAt, v))
}

// AcceptedAtGTE applies the GTE predicate on the "accepted_at" field.
func AcceptedAtGTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldAcceptedAt, v))
}

// AcceptedAtLT applies the LT predicate on the "accepted_at" field.
func AcceptedAtLT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldAcceptedAt, v))
}

// AcceptedAtLTE applies the LTE predicate on the "accepted_at" field.
func AcceptedAtLTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldAcceptedAt, v))
}

// DispatchStateEQ applies the EQ predicate on the "dispatch_state" field.
func DispatchStateEQ(v DispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldDispatchState, v))
}

// DispatchStateNEQ applies the NEQ predicate on the "dispatch_state" field.
func DispatchStateNEQ(v DispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldDispatchState, v))
}

// DispatchStateIn applies the In predicate on the "dispatch_state" field.
func DispatchStateIn(vs ...DispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldDispatchState, vs...))
}

// DispatchStateNotIn applies the NotIn predicate on the "dispatch_state" field.
func DispatchStateNotIn(vs ...DispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldDispatchState, vs...))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldAttemptCount, v))
}

// LeaseGenerationEQ applies the EQ predicate on the "lease_generation" field.
func LeaseGenerationEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLeaseGeneration, v))
}

// LeaseGenerationNEQ applies the NEQ predicate on the "lease_generation" field.
func LeaseGenerationNEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldLeaseGeneration, v))
}

// LeaseGenerationIn applies the In predicate on the "lease_generation" field.
func LeaseGenerationIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldLeaseGeneration, vs...))
}

// LeaseGenerationNotIn applies the NotIn predicate on the "lease_generation" field.
func LeaseGenerationNotIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldLeaseGeneration, vs...))
}

// LeaseGenerationGT applies the GT predicate on the "lease_generation" field.
func LeaseGenerationGT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldLeaseGeneration, v))
}

// LeaseGenerationGTE applies the GTE predicate on the "lease_generation" field.
func LeaseGenerationGTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldLeaseGeneration, v))
}

// LeaseGenerationLT applies the LT predicate on the "lease_generation" field.
func LeaseGenerationLT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldLeaseGeneration, v))
}

// LeaseGenerationLTE applies the LTE predicate on the "lease_generation" field.
func LeaseGenerationLTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldLeaseGeneration, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerIsNil applies the IsNil predicate on the "lease_owner" field.
func LeaseOwnerIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldLeaseOwner))
}

// LeaseOwnerNotNil applies the NotNil predicate on the "lease_owner" field.
func LeaseOwnerNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldLeaseOwner))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseUntilEQ applies the EQ predicate on the "lease_until" field.
func LeaseUntilEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLeaseUntil, v))
}

// LeaseUntilNEQ applies the NEQ predicate on the "lease_until" field.
func LeaseUntilNEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldLeaseUntil, v))
}

// LeaseUntilIn applies the In predicate on the "lease_until" field.
func LeaseUntilIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldLeaseUntil, vs...))
}

// LeaseUntilNotIn applies the NotIn predicate on the "lease_until" field.
func LeaseUntilNotIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldLeaseUntil, vs...))
}

// LeaseUntilGT applies the GT predicate on the "lease_until" field.
func LeaseUntilGT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldLeaseUntil, v))
}

// LeaseUntilGTE applies the GTE predicate on the "lease_until" field.
func LeaseUntilGTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldLeaseUntil, v))
}

// LeaseUntilLT applies the LT predicate on the "lease_until" field.
func LeaseUntilLT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldLeaseUntil, v))
}

// LeaseUntilLTE applies the LTE predicate on the "lease_until" field.
func LeaseUntilLTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldLeaseUntil, v))
}

// LeaseUntilIsNil applies the IsNil predicate on the "lease_until" field.
func LeaseUntilIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldLeaseUntil))
}

// LeaseUntilNotNil applies the NotNil predicate on the "lease_until" field.
func LeaseUntilNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldLeaseUntil))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldNextAttemptAt, v))
}

// NextAttemptAtIsNil applies the IsNil predicate on the "next_attempt_at" field.
func NextAttemptAtIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldNextAttemptAt))
}

// NextAttemptAtNotNil applies the NotNil predicate on the "next_attempt_at" field.
func NextAttemptAtNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldNextAttemptAt))
}

// RetryBlockedEQ applies the EQ predicate on the "retry_blocked" field.
func RetryBlockedEQ(v bool) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldRetryBlocked, v))
}

// RetryBlockedNEQ applies the NEQ predicate on the "retry_blocked" field.
func RetryBlockedNEQ(v bool) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldRetryBlocked, v))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeIsNil applies the IsNil predicate on the "last_error_code" field.
func LastErrorCodeIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldLastErrorCode))
}

// LastErrorCodeNotNil applies the NotNil predicate on the "last_error_code" field.
func LastErrorCodeNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldLastErrorCode))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// OwnerReceiptCanonicalEQ applies the EQ predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldOwnerReceiptCanonical, v))
}

// OwnerReceiptCanonicalNEQ applies the NEQ predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalNEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldOwnerReceiptCanonical, v))
}

// OwnerReceiptCanonicalIn applies the In predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldOwnerReceiptCanonical, vs...))
}

// OwnerReceiptCanonicalNotIn applies the NotIn predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalNotIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldOwnerReceiptCanonical, vs...))
}

// OwnerReceiptCanonicalGT applies the GT predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalGT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldOwnerReceiptCanonical, v))
}

// OwnerReceiptCanonicalGTE applies the GTE predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalGTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldOwnerReceiptCanonical, v))
}

// OwnerReceiptCanonicalLT applies the LT predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalLT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldOwnerReceiptCanonical, v))
}

// OwnerReceiptCanonicalLTE applies the LTE predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalLTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldOwnerReceiptCanonical, v))
}

// OwnerReceiptCanonicalIsNil applies the IsNil predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldOwnerReceiptCanonical))
}

// OwnerReceiptCanonicalNotNil applies the NotNil predicate on the "owner_receipt_canonical" field.
func OwnerReceiptCanonicalNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldOwnerReceiptCanonical))
}

// StopIntentGenerationEQ applies the EQ predicate on the "stop_intent_generation" field.
func StopIntentGenerationEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldStopIntentGeneration, v))
}

// StopIntentGenerationNEQ applies the NEQ predicate on the "stop_intent_generation" field.
func StopIntentGenerationNEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldStopIntentGeneration, v))
}

// StopIntentGenerationIn applies the In predicate on the "stop_intent_generation" field.
func StopIntentGenerationIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldStopIntentGeneration, vs...))
}

// StopIntentGenerationNotIn applies the NotIn predicate on the "stop_intent_generation" field.
func StopIntentGenerationNotIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldStopIntentGeneration, vs...))
}

// StopIntentGenerationGT applies the GT predicate on the "stop_intent_generation" field.
func StopIntentGenerationGT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldStopIntentGeneration, v))
}

// StopIntentGenerationGTE applies the GTE predicate on the "stop_intent_generation" field.
func StopIntentGenerationGTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldStopIntentGeneration, v))
}

// StopIntentGenerationLT applies the LT predicate on the "stop_intent_generation" field.
func StopIntentGenerationLT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldStopIntentGeneration, v))
}

// StopIntentGenerationLTE applies the LTE predicate on the "stop_intent_generation" field.
func StopIntentGenerationLTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldStopIntentGeneration, v))
}

// StopRequestedAtEQ applies the EQ predicate on the "stop_requested_at" field.
func StopRequestedAtEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldStopRequestedAt, v))
}

// StopRequestedAtNEQ applies the NEQ predicate on the "stop_requested_at" field.
func StopRequestedAtNEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldStopRequestedAt, v))
}

// StopRequestedAtIn applies the In predicate on the "stop_requested_at" field.
func StopRequestedAtIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldStopRequestedAt, vs...))
}

// StopRequestedAtNotIn applies the NotIn predicate on the "stop_requested_at" field.
func StopRequestedAtNotIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldStopRequestedAt, vs...))
}

// StopRequestedAtGT applies the GT predicate on the "stop_requested_at" field.
func StopRequestedAtGT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldStopRequestedAt, v))
}

// StopRequestedAtGTE applies the GTE predicate on the "stop_requested_at" field.
func StopRequestedAtGTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldStopRequestedAt, v))
}

// StopRequestedAtLT applies the LT predicate on the "stop_requested_at" field.
func StopRequestedAtLT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldStopRequestedAt, v))
}

// StopRequestedAtLTE applies the LTE predicate on the "stop_requested_at" field.
func StopRequestedAtLTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldStopRequestedAt, v))
}

// StopRequestedAtIsNil applies the IsNil predicate on the "stop_requested_at" field.
func StopRequestedAtIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldStopRequestedAt))
}

// StopRequestedAtNotNil applies the NotNil predicate on the "stop_requested_at" field.
func StopRequestedAtNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldStopRequestedAt))
}

// StopRequestedActorEQ applies the EQ predicate on the "stop_requested_actor" field.
func StopRequestedActorEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldStopRequestedActor, v))
}

// StopRequestedActorNEQ applies the NEQ predicate on the "stop_requested_actor" field.
func StopRequestedActorNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldStopRequestedActor, v))
}

// StopRequestedActorIn applies the In predicate on the "stop_requested_actor" field.
func StopRequestedActorIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldStopRequestedActor, vs...))
}

// StopRequestedActorNotIn applies the NotIn predicate on the "stop_requested_actor" field.
func StopRequestedActorNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldStopRequestedActor, vs...))
}

// StopRequestedActorGT applies the GT predicate on the "stop_requested_actor" field.
func StopRequestedActorGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldStopRequestedActor, v))
}

// StopRequestedActorGTE applies the GTE predicate on the "stop_requested_actor" field.
func StopRequestedActorGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldStopRequestedActor, v))
}

// StopRequestedActorLT applies the LT predicate on the "stop_requested_actor" field.
func StopRequestedActorLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldStopRequestedActor, v))
}

// StopRequestedActorLTE applies the LTE predicate on the "stop_requested_actor" field.
func StopRequestedActorLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldStopRequestedActor, v))
}

// StopRequestedActorContains applies the Contains predicate on the "stop_requested_actor" field.
func StopRequestedActorContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldStopRequestedActor, v))
}

// StopRequestedActorHasPrefix applies the HasPrefix predicate on the "stop_requested_actor" field.
func StopRequestedActorHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldStopRequestedActor, v))
}

// StopRequestedActorHasSuffix applies the HasSuffix predicate on the "stop_requested_actor" field.
func StopRequestedActorHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldStopRequestedActor, v))
}

// StopRequestedActorIsNil applies the IsNil predicate on the "stop_requested_actor" field.
func StopRequestedActorIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldStopRequestedActor))
}

// StopRequestedActorNotNil applies the NotNil predicate on the "stop_requested_actor" field.
func StopRequestedActorNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldStopRequestedActor))
}

// StopRequestedActorEqualFold applies the EqualFold predicate on the "stop_requested_actor" field.
func StopRequestedActorEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldStopRequestedActor, v))
}

// StopRequestedActorContainsFold applies the ContainsFold predicate on the "stop_requested_actor" field.
func StopRequestedActorContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldStopRequestedActor, v))
}

// CloseDispatchStateEQ applies the EQ predicate on the "close_dispatch_state" field.
func CloseDispatchStateEQ(v CloseDispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseDispatchState, v))
}

// CloseDispatchStateNEQ applies the NEQ predicate on the "close_dispatch_state" field.
func CloseDispatchStateNEQ(v CloseDispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseDispatchState, v))
}

// CloseDispatchStateIn applies the In predicate on the "close_dispatch_state" field.
func CloseDispatchStateIn(vs ...CloseDispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseDispatchState, vs...))
}

// CloseDispatchStateNotIn applies the NotIn predicate on the "close_dispatch_state" field.
func CloseDispatchStateNotIn(vs ...CloseDispatchState) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseDispatchState, vs...))
}

// CloseAttemptCountEQ applies the EQ predicate on the "close_attempt_count" field.
func CloseAttemptCountEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseAttemptCount, v))
}

// CloseAttemptCountNEQ applies the NEQ predicate on the "close_attempt_count" field.
func CloseAttemptCountNEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseAttemptCount, v))
}

// CloseAttemptCountIn applies the In predicate on the "close_attempt_count" field.
func CloseAttemptCountIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseAttemptCount, vs...))
}

// CloseAttemptCountNotIn applies the NotIn predicate on the "close_attempt_count" field.
func CloseAttemptCountNotIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseAttemptCount, vs...))
}

// CloseAttemptCountGT applies the GT predicate on the "close_attempt_count" field.
func CloseAttemptCountGT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseAttemptCount, v))
}

// CloseAttemptCountGTE applies the GTE predicate on the "close_attempt_count" field.
func CloseAttemptCountGTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseAttemptCount, v))
}

// CloseAttemptCountLT applies the LT predicate on the "close_attempt_count" field.
func CloseAttemptCountLT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseAttemptCount, v))
}

// CloseAttemptCountLTE applies the LTE predicate on the "close_attempt_count" field.
func CloseAttemptCountLTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseAttemptCount, v))
}

// CloseLeaseGenerationEQ applies the EQ predicate on the "close_lease_generation" field.
func CloseLeaseGenerationEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLeaseGeneration, v))
}

// CloseLeaseGenerationNEQ applies the NEQ predicate on the "close_lease_generation" field.
func CloseLeaseGenerationNEQ(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseLeaseGeneration, v))
}

// CloseLeaseGenerationIn applies the In predicate on the "close_lease_generation" field.
func CloseLeaseGenerationIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseLeaseGeneration, vs...))
}

// CloseLeaseGenerationNotIn applies the NotIn predicate on the "close_lease_generation" field.
func CloseLeaseGenerationNotIn(vs ...int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseLeaseGeneration, vs...))
}

// CloseLeaseGenerationGT applies the GT predicate on the "close_lease_generation" field.
func CloseLeaseGenerationGT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseLeaseGeneration, v))
}

// CloseLeaseGenerationGTE applies the GTE predicate on the "close_lease_generation" field.
func CloseLeaseGenerationGTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseLeaseGeneration, v))
}

// CloseLeaseGenerationLT applies the LT predicate on the "close_lease_generation" field.
func CloseLeaseGenerationLT(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseLeaseGeneration, v))
}

// CloseLeaseGenerationLTE applies the LTE predicate on the "close_lease_generation" field.
func CloseLeaseGenerationLTE(v int64) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseLeaseGeneration, v))
}

// CloseLeaseOwnerEQ applies the EQ predicate on the "close_lease_owner" field.
func CloseLeaseOwnerEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerNEQ applies the NEQ predicate on the "close_lease_owner" field.
func CloseLeaseOwnerNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerIn applies the In predicate on the "close_lease_owner" field.
func CloseLeaseOwnerIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseLeaseOwner, vs...))
}

// CloseLeaseOwnerNotIn applies the NotIn predicate on the "close_lease_owner" field.
func CloseLeaseOwnerNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseLeaseOwner, vs...))
}

// CloseLeaseOwnerGT applies the GT predicate on the "close_lease_owner" field.
func CloseLeaseOwnerGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerGTE applies the GTE predicate on the "close_lease_owner" field.
func CloseLeaseOwnerGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerLT applies the LT predicate on the "close_lease_owner" field.
func CloseLeaseOwnerLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerLTE applies the LTE predicate on the "close_lease_owner" field.
func CloseLeaseOwnerLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerContains applies the Contains predicate on the "close_lease_owner" field.
func CloseLeaseOwnerContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerHasPrefix applies the HasPrefix predicate on the "close_lease_owner" field.
func CloseLeaseOwnerHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerHasSuffix applies the HasSuffix predicate on the "close_lease_owner" field.
func CloseLeaseOwnerHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerIsNil applies the IsNil predicate on the "close_lease_owner" field.
func CloseLeaseOwnerIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldCloseLeaseOwner))
}

// CloseLeaseOwnerNotNil applies the NotNil predicate on the "close_lease_owner" field.
func CloseLeaseOwnerNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldCloseLeaseOwner))
}

// CloseLeaseOwnerEqualFold applies the EqualFold predicate on the "close_lease_owner" field.
func CloseLeaseOwnerEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldCloseLeaseOwner, v))
}

// CloseLeaseOwnerContainsFold applies the ContainsFold predicate on the "close_lease_owner" field.
func CloseLeaseOwnerContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldCloseLeaseOwner, v))
}

// CloseLeaseUntilEQ applies the EQ predicate on the "close_lease_until" field.
func CloseLeaseUntilEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLeaseUntil, v))
}

// CloseLeaseUntilNEQ applies the NEQ predicate on the "close_lease_until" field.
func CloseLeaseUntilNEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseLeaseUntil, v))
}

// CloseLeaseUntilIn applies the In predicate on the "close_lease_until" field.
func CloseLeaseUntilIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseLeaseUntil, vs...))
}

// CloseLeaseUntilNotIn applies the NotIn predicate on the "close_lease_until" field.
func CloseLeaseUntilNotIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseLeaseUntil, vs...))
}

// CloseLeaseUntilGT applies the GT predicate on the "close_lease_until" field.
func CloseLeaseUntilGT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseLeaseUntil, v))
}

// CloseLeaseUntilGTE applies the GTE predicate on the "close_lease_until" field.
func CloseLeaseUntilGTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseLeaseUntil, v))
}

// CloseLeaseUntilLT applies the LT predicate on the "close_lease_until" field.
func CloseLeaseUntilLT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseLeaseUntil, v))
}

// CloseLeaseUntilLTE applies the LTE predicate on the "close_lease_until" field.
func CloseLeaseUntilLTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseLeaseUntil, v))
}

// CloseLeaseUntilIsNil applies the IsNil predicate on the "close_lease_until" field.
func CloseLeaseUntilIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldCloseLeaseUntil))
}

// CloseLeaseUntilNotNil applies the NotNil predicate on the "close_lease_until" field.
func CloseLeaseUntilNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldCloseLeaseUntil))
}

// CloseNextAttemptAtEQ applies the EQ predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseNextAttemptAt, v))
}

// CloseNextAttemptAtNEQ applies the NEQ predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtNEQ(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseNextAttemptAt, v))
}

// CloseNextAttemptAtIn applies the In predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseNextAttemptAt, vs...))
}

// CloseNextAttemptAtNotIn applies the NotIn predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtNotIn(vs ...time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseNextAttemptAt, vs...))
}

// CloseNextAttemptAtGT applies the GT predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtGT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseNextAttemptAt, v))
}

// CloseNextAttemptAtGTE applies the GTE predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtGTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseNextAttemptAt, v))
}

// CloseNextAttemptAtLT applies the LT predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtLT(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseNextAttemptAt, v))
}

// CloseNextAttemptAtLTE applies the LTE predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtLTE(v time.Time) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseNextAttemptAt, v))
}

// CloseNextAttemptAtIsNil applies the IsNil predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldCloseNextAttemptAt))
}

// CloseNextAttemptAtNotNil applies the NotNil predicate on the "close_next_attempt_at" field.
func CloseNextAttemptAtNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldCloseNextAttemptAt))
}

// CloseRetryBlockedEQ applies the EQ predicate on the "close_retry_blocked" field.
func CloseRetryBlockedEQ(v bool) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseRetryBlocked, v))
}

// CloseRetryBlockedNEQ applies the NEQ predicate on the "close_retry_blocked" field.
func CloseRetryBlockedNEQ(v bool) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseRetryBlocked, v))
}

// CloseLastErrorCodeEQ applies the EQ predicate on the "close_last_error_code" field.
func CloseLastErrorCodeEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeNEQ applies the NEQ predicate on the "close_last_error_code" field.
func CloseLastErrorCodeNEQ(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeIn applies the In predicate on the "close_last_error_code" field.
func CloseLastErrorCodeIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseLastErrorCode, vs...))
}

// CloseLastErrorCodeNotIn applies the NotIn predicate on the "close_last_error_code" field.
func CloseLastErrorCodeNotIn(vs ...string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseLastErrorCode, vs...))
}

// CloseLastErrorCodeGT applies the GT predicate on the "close_last_error_code" field.
func CloseLastErrorCodeGT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeGTE applies the GTE predicate on the "close_last_error_code" field.
func CloseLastErrorCodeGTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeLT applies the LT predicate on the "close_last_error_code" field.
func CloseLastErrorCodeLT(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeLTE applies the LTE predicate on the "close_last_error_code" field.
func CloseLastErrorCodeLTE(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeContains applies the Contains predicate on the "close_last_error_code" field.
func CloseLastErrorCodeContains(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContains(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeHasPrefix applies the HasPrefix predicate on the "close_last_error_code" field.
func CloseLastErrorCodeHasPrefix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasPrefix(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeHasSuffix applies the HasSuffix predicate on the "close_last_error_code" field.
func CloseLastErrorCodeHasSuffix(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldHasSuffix(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeIsNil applies the IsNil predicate on the "close_last_error_code" field.
func CloseLastErrorCodeIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldCloseLastErrorCode))
}

// CloseLastErrorCodeNotNil applies the NotNil predicate on the "close_last_error_code" field.
func CloseLastErrorCodeNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldCloseLastErrorCode))
}

// CloseLastErrorCodeEqualFold applies the EqualFold predicate on the "close_last_error_code" field.
func CloseLastErrorCodeEqualFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEqualFold(FieldCloseLastErrorCode, v))
}

// CloseLastErrorCodeContainsFold applies the ContainsFold predicate on the "close_last_error_code" field.
func CloseLastErrorCodeContainsFold(v string) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldContainsFold(FieldCloseLastErrorCode, v))
}

// CloseReceiptCanonicalEQ applies the EQ predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldEQ(FieldCloseReceiptCanonical, v))
}

// CloseReceiptCanonicalNEQ applies the NEQ predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalNEQ(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNEQ(FieldCloseReceiptCanonical, v))
}

// CloseReceiptCanonicalIn applies the In predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIn(FieldCloseReceiptCanonical, vs...))
}

// CloseReceiptCanonicalNotIn applies the NotIn predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalNotIn(vs ...[]byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotIn(FieldCloseReceiptCanonical, vs...))
}

// CloseReceiptCanonicalGT applies the GT predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalGT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGT(FieldCloseReceiptCanonical, v))
}

// CloseReceiptCanonicalGTE applies the GTE predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalGTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldGTE(FieldCloseReceiptCanonical, v))
}

// CloseReceiptCanonicalLT applies the LT predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalLT(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLT(FieldCloseReceiptCanonical, v))
}

// CloseReceiptCanonicalLTE applies the LTE predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalLTE(v []byte) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldLTE(FieldCloseReceiptCanonical, v))
}

// CloseReceiptCanonicalIsNil applies the IsNil predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalIsNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldIsNull(FieldCloseReceiptCanonical))
}

// CloseReceiptCanonicalNotNil applies the NotNil predicate on the "close_receipt_canonical" field.
func CloseReceiptCanonicalNotNil() predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.FieldNotNull(FieldCloseReceiptCanonical))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelDevAcceptance) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelDevAcceptance) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelDevAcceptance) predicate.ModelDevAcceptance {
	return predicate.ModelDevAcceptance(sql.NotPredicates(p))
}
