syntax = "proto3";

package script.service.v1;

import "errors/errors.proto";

// 脚本管理错误定义
enum ScriptErrorReason {
    option (errors.default_code) = 500;

    // 400
    BAD_REQUEST = 0 [(errors.code) = 400]; // 错误请求

    // 401
    UNAUTHORIZED = 100 [(errors.code) = 401]; // 未授权

    // 403
    FORBIDDEN = 300 [(errors.code) = 403]; // 禁止访问

    // 404
    NOT_FOUND = 400 [(errors.code) = 404]; // 找不到资源

    // 409
    CONFLICT = 900 [(errors.code) = 409]; // 冲突（如脚本名已存在）

    // 422
    UNPROCESSABLE_ENTITY = 1100 [(errors.code) = 422]; // 脚本语法/校验失败

    // 429
    TOO_MANY_REQUESTS = 1160 [(errors.code) = 429]; // 请求过多

    // 500
    INTERNAL_SERVER_ERROR = 2000 [(errors.code) = 500]; // 内部服务器错误

    // 501
    NOT_IMPLEMENTED = 2100 [(errors.code) = 501]; // 未实现
}
