// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/internalmessagerecipient"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 站内信消息用户接收信息表
type InternalMessageRecipient struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 站内信内容ID
	MessageID *uint32 `json:"message_id,omitempty"`
	// 接收者用户ID
	RecipientUserID *uint32 `json:"recipient_user_id,omitempty"`
	// 消息状态
	Status *internalmessagerecipient.Status `json:"status,omitempty"`
	// 消息到达用户收件箱的时间
	ReceivedAt *time.Time `json:"received_at,omitempty"`
	// 用户阅读消息的时间
	ReadAt       *time.Time `json:"read_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InternalMessageRecipient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case internalmessagerecipient.FieldID, internalmessagerecipient.FieldTenantID, internalmessagerecipient.FieldMessageID, internalmessagerecipient.FieldRecipientUserID:
			values[i] = new(sql.NullInt64)
		case internalmessagerecipient.FieldStatus:
			values[i] = new(sql.NullString)
		case internalmessagerecipient.FieldCreatedAt, internalmessagerecipient.FieldUpdatedAt, internalmessagerecipient.FieldDeletedAt, internalmessagerecipient.FieldReceivedAt, internalmessagerecipient.FieldReadAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InternalMessageRecipient fields.
func (_m *InternalMessageRecipient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case internalmessagerecipient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case internalmessagerecipient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case internalmessagerecipient.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case internalmessagerecipient.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case internalmessagerecipient.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case internalmessagerecipient.FieldMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = new(uint32)
				*_m.MessageID = uint32(value.Int64)
			}
		case internalmessagerecipient.FieldRecipientUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_user_id", values[i])
			} else if value.Valid {
				_m.RecipientUserID = new(uint32)
				*_m.RecipientUserID = uint32(value.Int64)
			}
		case internalmessagerecipient.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(internalmessagerecipient.Status)
				*_m.Status = internalmessagerecipient.Status(value.String)
			}
		case internalmessagerecipient.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = new(time.Time)
				*_m.ReceivedAt = value.Time
			}
		case internalmessagerecipient.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = new(time.Time)
				*_m.ReadAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InternalMessageRecipient.
// This includes values selected through modifiers, order, etc.
func (_m *InternalMessageRecipient) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InternalMessageRecipient.
// Note that you need to call InternalMessageRecipient.Unwrap() before calling this method if this InternalMessageRecipient
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InternalMessageRecipient) Update() *InternalMessageRecipientUpdateOne {
	return NewInternalMessageRecipientClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InternalMessageRecipient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InternalMessageRecipient) Unwrap() *InternalMessageRecipient {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InternalMessageRecipient is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InternalMessageRecipient) String() string {
	var builder strings.Builder
	builder.WriteString("InternalMessageRecipient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MessageID; v != nil {
		builder.WriteString("message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RecipientUserID; v != nil {
		builder.WriteString("recipient_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReceivedAt; v != nil {
		builder.WriteString("received_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReadAt; v != nil {
		builder.WriteString("read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InternalMessageRecipients is a parsable slice of InternalMessageRecipient.
type InternalMessageRecipients []*InternalMessageRecipient
