// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/modeldevacceptance"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModelDevAcceptanceCreate is the builder for creating a ModelDevAcceptance entity.
type ModelDevAcceptanceCreate struct {
	config
	mutation *ModelDevAcceptanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *ModelDevAcceptanceCreate) SetTenantID(v uint32) *ModelDevAcceptanceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetResourceTenantID sets the "resource_tenant_id" field.
func (_c *ModelDevAcceptanceCreate) SetResourceTenantID(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetResourceTenantID(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *ModelDevAcceptanceCreate) SetActor(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *ModelDevAcceptanceCreate) SetAction(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ModelDevAcceptanceCreate) SetIdempotencyKey(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetOperationID sets the "operation_id" field.
func (_c *ModelDevAcceptanceCreate) SetOperationID(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *ModelDevAcceptanceCreate) SetExecutionID(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetIntentHash sets the "intent_hash" field.
func (_c *ModelDevAcceptanceCreate) SetIntentHash(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetIntentHash(v)
	return _c
}

// SetIntentCanonical sets the "intent_canonical" field.
func (_c *ModelDevAcceptanceCreate) SetIntentCanonical(v []byte) *ModelDevAcceptanceCreate {
	_c.mutation.SetIntentCanonical(v)
	return _c
}

// SetExecutionSpecHash sets the "execution_spec_hash" field.
func (_c *ModelDevAcceptanceCreate) SetExecutionSpecHash(v string) *ModelDevAcceptanceCreate {
	_c.mutation.SetExecutionSpecHash(v)
	return _c
}

// SetSnapshotCanonical sets the "snapshot_canonical" field.
func (_c *ModelDevAcceptanceCreate) SetSnapshotCanonical(v []byte) *ModelDevAcceptanceCreate {
	_c.mutation.SetSnapshotCanonical(v)
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *ModelDevAcceptanceCreate) SetAcceptedAt(v time.Time) *ModelDevAcceptanceCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetDispatchState sets the "dispatch_state" field.
func (_c *ModelDevAcceptanceCreate) SetDispatchState(v modeldevacceptance.DispatchState) *ModelDevAcceptanceCreate {
	_c.mutation.SetDispatchState(v)
	return _c
}

// SetNillableDispatchState sets the "dispatch_state" field if the given value is not nil.
func (_c *ModelDevAcceptanceCreate) SetNillableDispatchState(v *modeldevacceptance.DispatchState) *ModelDevAcceptanceCreate {
	if v != nil {
		_c.SetDispatchState(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelDevAcceptanceCreate) SetID(v uint32) *ModelDevAcceptanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ModelDevAcceptanceMutation object of the builder.
func (_c *ModelDevAcceptanceCreate) Mutation() *ModelDevAcceptanceMutation {
	return _c.mutation
}

// Save creates the ModelDevAcceptance in the database.
func (_c *ModelDevAcceptanceCreate) Save(ctx context.Context) (*ModelDevAcceptance, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelDevAcceptanceCreate) SaveX(ctx context.Context) *ModelDevAcceptance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelDevAcceptanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelDevAcceptanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelDevAcceptanceCreate) defaults() error {
	if _, ok := _c.mutation.DispatchState(); !ok {
		v := modeldevacceptance.DefaultDispatchState
		_c.mutation.SetDispatchState(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelDevAcceptanceCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ModelDevAcceptance.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := modeldevacceptance.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceTenantID(); !ok {
		return &ValidationError{Name: "resource_tenant_id", err: errors.New(`ent: missing required field "ModelDevAcceptance.resource_tenant_id"`)}
	}
	if v, ok := _c.mutation.ResourceTenantID(); ok {
		if err := modeldevacceptance.ResourceTenantIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_tenant_id", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.resource_tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "ModelDevAcceptance.actor"`)}
	}
	if v, ok := _c.mutation.Actor(); ok {
		if err := modeldevacceptance.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.actor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "ModelDevAcceptance.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := modeldevacceptance.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "ModelDevAcceptance.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := modeldevacceptance.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "ModelDevAcceptance.operation_id"`)}
	}
	if v, ok := _c.mutation.OperationID(); ok {
		if err := modeldevacceptance.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.operation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "ModelDevAcceptance.execution_id"`)}
	}
	if v, ok := _c.mutation.ExecutionID(); ok {
		if err := modeldevacceptance.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.execution_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntentHash(); !ok {
		return &ValidationError{Name: "intent_hash", err: errors.New(`ent: missing required field "ModelDevAcceptance.intent_hash"`)}
	}
	if v, ok := _c.mutation.IntentHash(); ok {
		if err := modeldevacceptance.IntentHashValidator(v); err != nil {
			return &ValidationError{Name: "intent_hash", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.intent_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntentCanonical(); !ok {
		return &ValidationError{Name: "intent_canonical", err: errors.New(`ent: missing required field "ModelDevAcceptance.intent_canonical"`)}
	}
	if v, ok := _c.mutation.IntentCanonical(); ok {
		if err := modeldevacceptance.IntentCanonicalValidator(v); err != nil {
			return &ValidationError{Name: "intent_canonical", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.intent_canonical": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionSpecHash(); !ok {
		return &ValidationError{Name: "execution_spec_hash", err: errors.New(`ent: missing required field "ModelDevAcceptance.execution_spec_hash"`)}
	}
	if v, ok := _c.mutation.ExecutionSpecHash(); ok {
		if err := modeldevacceptance.ExecutionSpecHashValidator(v); err != nil {
			return &ValidationError{Name: "execution_spec_hash", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.execution_spec_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SnapshotCanonical(); !ok {
		return &ValidationError{Name: "snapshot_canonical", err: errors.New(`ent: missing required field "ModelDevAcceptance.snapshot_canonical"`)}
	}
	if v, ok := _c.mutation.SnapshotCanonical(); ok {
		if err := modeldevacceptance.SnapshotCanonicalValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_canonical", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.snapshot_canonical": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AcceptedAt(); !ok {
		return &ValidationError{Name: "accepted_at", err: errors.New(`ent: missing required field "ModelDevAcceptance.accepted_at"`)}
	}
	if _, ok := _c.mutation.DispatchState(); !ok {
		return &ValidationError{Name: "dispatch_state", err: errors.New(`ent: missing required field "ModelDevAcceptance.dispatch_state"`)}
	}
	if v, ok := _c.mutation.DispatchState(); ok {
		if err := modeldevacceptance.DispatchStateValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_state", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.dispatch_state": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := modeldevacceptance.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ModelDevAcceptanceCreate) sqlSave(ctx context.Context) (*ModelDevAcceptance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelDevAcceptanceCreate) createSpec() (*ModelDevAcceptance, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelDevAcceptance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modeldevacceptance.Table, sqlgraph.NewFieldSpec(modeldevacceptance.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(modeldevacceptance.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ResourceTenantID(); ok {
		_spec.SetField(modeldevacceptance.FieldResourceTenantID, field.TypeString, value)
		_node.ResourceTenantID = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(modeldevacceptance.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(modeldevacceptance.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(modeldevacceptance.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(modeldevacceptance.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.ExecutionID(); ok {
		_spec.SetField(modeldevacceptance.FieldExecutionID, field.TypeString, value)
		_node.ExecutionID = value
	}
	if value, ok := _c.mutation.IntentHash(); ok {
		_spec.SetField(modeldevacceptance.FieldIntentHash, field.TypeString, value)
		_node.IntentHash = value
	}
	if value, ok := _c.mutation.IntentCanonical(); ok {
		_spec.SetField(modeldevacceptance.FieldIntentCanonical, field.TypeBytes, value)
		_node.IntentCanonical = value
	}
	if value, ok := _c.mutation.ExecutionSpecHash(); ok {
		_spec.SetField(modeldevacceptance.FieldExecutionSpecHash, field.TypeString, value)
		_node.ExecutionSpecHash = value
	}
	if value, ok := _c.mutation.SnapshotCanonical(); ok {
		_spec.SetField(modeldevacceptance.FieldSnapshotCanonical, field.TypeBytes, value)
		_node.SnapshotCanonical = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(modeldevacceptance.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = value
	}
	if value, ok := _c.mutation.DispatchState(); ok {
		_spec.SetField(modeldevacceptance.FieldDispatchState, field.TypeEnum, value)
		_node.DispatchState = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelDevAcceptance.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelDevAcceptanceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelDevAcceptanceCreate) OnConflict(opts ...sql.ConflictOption) *ModelDevAcceptanceUpsertOne {
	_c.conflict = opts
	return &ModelDevAcceptanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelDevAcceptance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelDevAcceptanceCreate) OnConflictColumns(columns ...string) *ModelDevAcceptanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelDevAcceptanceUpsertOne{
		create: _c,
	}
}

type (
	// ModelDevAcceptanceUpsertOne is the builder for "upsert"-ing
	//  one ModelDevAcceptance node.
	ModelDevAcceptanceUpsertOne struct {
		create *ModelDevAcceptanceCreate
	}

	// ModelDevAcceptanceUpsert is the "OnConflict" setter.
	ModelDevAcceptanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetDispatchState sets the "dispatch_state" field.
func (u *ModelDevAcceptanceUpsert) SetDispatchState(v modeldevacceptance.DispatchState) *ModelDevAcceptanceUpsert {
	u.Set(modeldevacceptance.FieldDispatchState, v)
	return u
}

// UpdateDispatchState sets the "dispatch_state" field to the value that was provided on create.
func (u *ModelDevAcceptanceUpsert) UpdateDispatchState() *ModelDevAcceptanceUpsert {
	u.SetExcluded(modeldevacceptance.FieldDispatchState)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ModelDevAcceptance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(modeldevacceptance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ModelDevAcceptanceUpsertOne) UpdateNewValues() *ModelDevAcceptanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(modeldevacceptance.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(modeldevacceptance.FieldTenantID)
		}
		if _, exists := u.create.mutation.ResourceTenantID(); exists {
			s.SetIgnore(modeldevacceptance.FieldResourceTenantID)
		}
		if _, exists := u.create.mutation.Actor(); exists {
			s.SetIgnore(modeldevacceptance.FieldActor)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(modeldevacceptance.FieldAction)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(modeldevacceptance.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.OperationID(); exists {
			s.SetIgnore(modeldevacceptance.FieldOperationID)
		}
		if _, exists := u.create.mutation.ExecutionID(); exists {
			s.SetIgnore(modeldevacceptance.FieldExecutionID)
		}
		if _, exists := u.create.mutation.IntentHash(); exists {
			s.SetIgnore(modeldevacceptance.FieldIntentHash)
		}
		if _, exists := u.create.mutation.IntentCanonical(); exists {
			s.SetIgnore(modeldevacceptance.FieldIntentCanonical)
		}
		if _, exists := u.create.mutation.ExecutionSpecHash(); exists {
			s.SetIgnore(modeldevacceptance.FieldExecutionSpecHash)
		}
		if _, exists := u.create.mutation.SnapshotCanonical(); exists {
			s.SetIgnore(modeldevacceptance.FieldSnapshotCanonical)
		}
		if _, exists := u.create.mutation.AcceptedAt(); exists {
			s.SetIgnore(modeldevacceptance.FieldAcceptedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelDevAcceptance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelDevAcceptanceUpsertOne) Ignore() *ModelDevAcceptanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelDevAcceptanceUpsertOne) DoNothing() *ModelDevAcceptanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelDevAcceptanceCreate.OnConflict
// documentation for more info.
func (u *ModelDevAcceptanceUpsertOne) Update(set func(*ModelDevAcceptanceUpsert)) *ModelDevAcceptanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelDevAcceptanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetDispatchState sets the "dispatch_state" field.
func (u *ModelDevAcceptanceUpsertOne) SetDispatchState(v modeldevacceptance.DispatchState) *ModelDevAcceptanceUpsertOne {
	return u.Update(func(s *ModelDevAcceptanceUpsert) {
		s.SetDispatchState(v)
	})
}

// UpdateDispatchState sets the "dispatch_state" field to the value that was provided on create.
func (u *ModelDevAcceptanceUpsertOne) UpdateDispatchState() *ModelDevAcceptanceUpsertOne {
	return u.Update(func(s *ModelDevAcceptanceUpsert) {
		s.UpdateDispatchState()
	})
}

// Exec executes the query.
func (u *ModelDevAcceptanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelDevAcceptanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelDevAcceptanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelDevAcceptanceUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelDevAcceptanceUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelDevAcceptanceCreateBulk is the builder for creating many ModelDevAcceptance entities in bulk.
type ModelDevAcceptanceCreateBulk struct {
	config
	err      error
	builders []*ModelDevAcceptanceCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelDevAcceptance entities in the database.
func (_c *ModelDevAcceptanceCreateBulk) Save(ctx context.Context) ([]*ModelDevAcceptance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelDevAcceptance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelDevAcceptanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelDevAcceptanceCreateBulk) SaveX(ctx context.Context) []*ModelDevAcceptance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelDevAcceptanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelDevAcceptanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelDevAcceptance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelDevAcceptanceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelDevAcceptanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelDevAcceptanceUpsertBulk {
	_c.conflict = opts
	return &ModelDevAcceptanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelDevAcceptance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelDevAcceptanceCreateBulk) OnConflictColumns(columns ...string) *ModelDevAcceptanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelDevAcceptanceUpsertBulk{
		create: _c,
	}
}

// ModelDevAcceptanceUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelDevAcceptance nodes.
type ModelDevAcceptanceUpsertBulk struct {
	create *ModelDevAcceptanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelDevAcceptance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(modeldevacceptance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ModelDevAcceptanceUpsertBulk) UpdateNewValues() *ModelDevAcceptanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(modeldevacceptance.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(modeldevacceptance.FieldTenantID)
			}
			if _, exists := b.mutation.ResourceTenantID(); exists {
				s.SetIgnore(modeldevacceptance.FieldResourceTenantID)
			}
			if _, exists := b.mutation.Actor(); exists {
				s.SetIgnore(modeldevacceptance.FieldActor)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(modeldevacceptance.FieldAction)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(modeldevacceptance.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.OperationID(); exists {
				s.SetIgnore(modeldevacceptance.FieldOperationID)
			}
			if _, exists := b.mutation.ExecutionID(); exists {
				s.SetIgnore(modeldevacceptance.FieldExecutionID)
			}
			if _, exists := b.mutation.IntentHash(); exists {
				s.SetIgnore(modeldevacceptance.FieldIntentHash)
			}
			if _, exists := b.mutation.IntentCanonical(); exists {
				s.SetIgnore(modeldevacceptance.FieldIntentCanonical)
			}
			if _, exists := b.mutation.ExecutionSpecHash(); exists {
				s.SetIgnore(modeldevacceptance.FieldExecutionSpecHash)
			}
			if _, exists := b.mutation.SnapshotCanonical(); exists {
				s.SetIgnore(modeldevacceptance.FieldSnapshotCanonical)
			}
			if _, exists := b.mutation.AcceptedAt(); exists {
				s.SetIgnore(modeldevacceptance.FieldAcceptedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelDevAcceptance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelDevAcceptanceUpsertBulk) Ignore() *ModelDevAcceptanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelDevAcceptanceUpsertBulk) DoNothing() *ModelDevAcceptanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelDevAcceptanceCreateBulk.OnConflict
// documentation for more info.
func (u *ModelDevAcceptanceUpsertBulk) Update(set func(*ModelDevAcceptanceUpsert)) *ModelDevAcceptanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelDevAcceptanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetDispatchState sets the "dispatch_state" field.
func (u *ModelDevAcceptanceUpsertBulk) SetDispatchState(v modeldevacceptance.DispatchState) *ModelDevAcceptanceUpsertBulk {
	return u.Update(func(s *ModelDevAcceptanceUpsert) {
		s.SetDispatchState(v)
	})
}

// UpdateDispatchState sets the "dispatch_state" field to the value that was provided on create.
func (u *ModelDevAcceptanceUpsertBulk) UpdateDispatchState() *ModelDevAcceptanceUpsertBulk {
	return u.Update(func(s *ModelDevAcceptanceUpsert) {
		s.UpdateDispatchState()
	})
}

// Exec executes the query.
func (u *ModelDevAcceptanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelDevAcceptanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelDevAcceptanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelDevAcceptanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
