// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/modeldevacceptance"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModelDevAcceptanceUpdate is the builder for updating ModelDevAcceptance entities.
type ModelDevAcceptanceUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelDevAcceptanceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelDevAcceptanceUpdate builder.
func (_u *ModelDevAcceptanceUpdate) Where(ps ...predicate.ModelDevAcceptance) *ModelDevAcceptanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDispatchState sets the "dispatch_state" field.
func (_u *ModelDevAcceptanceUpdate) SetDispatchState(v modeldevacceptance.DispatchState) *ModelDevAcceptanceUpdate {
	_u.mutation.SetDispatchState(v)
	return _u
}

// SetNillableDispatchState sets the "dispatch_state" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableDispatchState(v *modeldevacceptance.DispatchState) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetDispatchState(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *ModelDevAcceptanceUpdate) SetAttemptCount(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableAttemptCount(v *int64) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *ModelDevAcceptanceUpdate) AddAttemptCount(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLeaseGeneration sets the "lease_generation" field.
func (_u *ModelDevAcceptanceUpdate) SetLeaseGeneration(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.ResetLeaseGeneration()
	_u.mutation.SetLeaseGeneration(v)
	return _u
}

// SetNillableLeaseGeneration sets the "lease_generation" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableLeaseGeneration(v *int64) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetLeaseGeneration(*v)
	}
	return _u
}

// AddLeaseGeneration adds value to the "lease_generation" field.
func (_u *ModelDevAcceptanceUpdate) AddLeaseGeneration(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.AddLeaseGeneration(v)
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *ModelDevAcceptanceUpdate) SetLeaseOwner(v string) *ModelDevAcceptanceUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableLeaseOwner(v *string) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *ModelDevAcceptanceUpdate) ClearLeaseOwner() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseUntil sets the "lease_until" field.
func (_u *ModelDevAcceptanceUpdate) SetLeaseUntil(v time.Time) *ModelDevAcceptanceUpdate {
	_u.mutation.SetLeaseUntil(v)
	return _u
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableLeaseUntil(v *time.Time) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetLeaseUntil(*v)
	}
	return _u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (_u *ModelDevAcceptanceUpdate) ClearLeaseUntil() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearLeaseUntil()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdate) SetNextAttemptAt(v time.Time) *ModelDevAcceptanceUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableNextAttemptAt(v *time.Time) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdate) ClearNextAttemptAt() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetRetryBlocked sets the "retry_blocked" field.
func (_u *ModelDevAcceptanceUpdate) SetRetryBlocked(v bool) *ModelDevAcceptanceUpdate {
	_u.mutation.SetRetryBlocked(v)
	return _u
}

// SetNillableRetryBlocked sets the "retry_blocked" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableRetryBlocked(v *bool) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetRetryBlocked(*v)
	}
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *ModelDevAcceptanceUpdate) SetLastErrorCode(v string) *ModelDevAcceptanceUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableLastErrorCode(v *string) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *ModelDevAcceptanceUpdate) ClearLastErrorCode() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetOwnerReceiptCanonical sets the "owner_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdate) SetOwnerReceiptCanonical(v []byte) *ModelDevAcceptanceUpdate {
	_u.mutation.SetOwnerReceiptCanonical(v)
	return _u
}

// ClearOwnerReceiptCanonical clears the value of the "owner_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdate) ClearOwnerReceiptCanonical() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearOwnerReceiptCanonical()
	return _u
}

// SetStopIntentGeneration sets the "stop_intent_generation" field.
func (_u *ModelDevAcceptanceUpdate) SetStopIntentGeneration(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.ResetStopIntentGeneration()
	_u.mutation.SetStopIntentGeneration(v)
	return _u
}

// SetNillableStopIntentGeneration sets the "stop_intent_generation" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableStopIntentGeneration(v *int64) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetStopIntentGeneration(*v)
	}
	return _u
}

// AddStopIntentGeneration adds value to the "stop_intent_generation" field.
func (_u *ModelDevAcceptanceUpdate) AddStopIntentGeneration(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.AddStopIntentGeneration(v)
	return _u
}

// SetStopRequestedAt sets the "stop_requested_at" field.
func (_u *ModelDevAcceptanceUpdate) SetStopRequestedAt(v time.Time) *ModelDevAcceptanceUpdate {
	_u.mutation.SetStopRequestedAt(v)
	return _u
}

// SetNillableStopRequestedAt sets the "stop_requested_at" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableStopRequestedAt(v *time.Time) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetStopRequestedAt(*v)
	}
	return _u
}

// ClearStopRequestedAt clears the value of the "stop_requested_at" field.
func (_u *ModelDevAcceptanceUpdate) ClearStopRequestedAt() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearStopRequestedAt()
	return _u
}

// SetStopRequestedActor sets the "stop_requested_actor" field.
func (_u *ModelDevAcceptanceUpdate) SetStopRequestedActor(v string) *ModelDevAcceptanceUpdate {
	_u.mutation.SetStopRequestedActor(v)
	return _u
}

// SetNillableStopRequestedActor sets the "stop_requested_actor" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableStopRequestedActor(v *string) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetStopRequestedActor(*v)
	}
	return _u
}

// ClearStopRequestedActor clears the value of the "stop_requested_actor" field.
func (_u *ModelDevAcceptanceUpdate) ClearStopRequestedActor() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearStopRequestedActor()
	return _u
}

// SetCloseDispatchState sets the "close_dispatch_state" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseDispatchState(v modeldevacceptance.CloseDispatchState) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseDispatchState(v)
	return _u
}

// SetNillableCloseDispatchState sets the "close_dispatch_state" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseDispatchState(v *modeldevacceptance.CloseDispatchState) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseDispatchState(*v)
	}
	return _u
}

// SetCloseAttemptCount sets the "close_attempt_count" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseAttemptCount(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.ResetCloseAttemptCount()
	_u.mutation.SetCloseAttemptCount(v)
	return _u
}

// SetNillableCloseAttemptCount sets the "close_attempt_count" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseAttemptCount(v *int64) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseAttemptCount(*v)
	}
	return _u
}

// AddCloseAttemptCount adds value to the "close_attempt_count" field.
func (_u *ModelDevAcceptanceUpdate) AddCloseAttemptCount(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.AddCloseAttemptCount(v)
	return _u
}

// SetCloseLeaseGeneration sets the "close_lease_generation" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseLeaseGeneration(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.ResetCloseLeaseGeneration()
	_u.mutation.SetCloseLeaseGeneration(v)
	return _u
}

// SetNillableCloseLeaseGeneration sets the "close_lease_generation" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseLeaseGeneration(v *int64) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseLeaseGeneration(*v)
	}
	return _u
}

// AddCloseLeaseGeneration adds value to the "close_lease_generation" field.
func (_u *ModelDevAcceptanceUpdate) AddCloseLeaseGeneration(v int64) *ModelDevAcceptanceUpdate {
	_u.mutation.AddCloseLeaseGeneration(v)
	return _u
}

// SetCloseLeaseOwner sets the "close_lease_owner" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseLeaseOwner(v string) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseLeaseOwner(v)
	return _u
}

// SetNillableCloseLeaseOwner sets the "close_lease_owner" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseLeaseOwner(v *string) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseLeaseOwner(*v)
	}
	return _u
}

// ClearCloseLeaseOwner clears the value of the "close_lease_owner" field.
func (_u *ModelDevAcceptanceUpdate) ClearCloseLeaseOwner() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearCloseLeaseOwner()
	return _u
}

// SetCloseLeaseUntil sets the "close_lease_until" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseLeaseUntil(v time.Time) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseLeaseUntil(v)
	return _u
}

// SetNillableCloseLeaseUntil sets the "close_lease_until" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseLeaseUntil(v *time.Time) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseLeaseUntil(*v)
	}
	return _u
}

// ClearCloseLeaseUntil clears the value of the "close_lease_until" field.
func (_u *ModelDevAcceptanceUpdate) ClearCloseLeaseUntil() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearCloseLeaseUntil()
	return _u
}

// SetCloseNextAttemptAt sets the "close_next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseNextAttemptAt(v time.Time) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseNextAttemptAt(v)
	return _u
}

// SetNillableCloseNextAttemptAt sets the "close_next_attempt_at" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseNextAttemptAt(v *time.Time) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseNextAttemptAt(*v)
	}
	return _u
}

// ClearCloseNextAttemptAt clears the value of the "close_next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdate) ClearCloseNextAttemptAt() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearCloseNextAttemptAt()
	return _u
}

// SetCloseRetryBlocked sets the "close_retry_blocked" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseRetryBlocked(v bool) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseRetryBlocked(v)
	return _u
}

// SetNillableCloseRetryBlocked sets the "close_retry_blocked" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseRetryBlocked(v *bool) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseRetryBlocked(*v)
	}
	return _u
}

// SetCloseLastErrorCode sets the "close_last_error_code" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseLastErrorCode(v string) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseLastErrorCode(v)
	return _u
}

// SetNillableCloseLastErrorCode sets the "close_last_error_code" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdate) SetNillableCloseLastErrorCode(v *string) *ModelDevAcceptanceUpdate {
	if v != nil {
		_u.SetCloseLastErrorCode(*v)
	}
	return _u
}

// ClearCloseLastErrorCode clears the value of the "close_last_error_code" field.
func (_u *ModelDevAcceptanceUpdate) ClearCloseLastErrorCode() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearCloseLastErrorCode()
	return _u
}

// SetCloseReceiptCanonical sets the "close_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdate) SetCloseReceiptCanonical(v []byte) *ModelDevAcceptanceUpdate {
	_u.mutation.SetCloseReceiptCanonical(v)
	return _u
}

// ClearCloseReceiptCanonical clears the value of the "close_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdate) ClearCloseReceiptCanonical() *ModelDevAcceptanceUpdate {
	_u.mutation.ClearCloseReceiptCanonical()
	return _u
}

// Mutation returns the ModelDevAcceptanceMutation object of the builder.
func (_u *ModelDevAcceptanceUpdate) Mutation() *ModelDevAcceptanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelDevAcceptanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelDevAcceptanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelDevAcceptanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelDevAcceptanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelDevAcceptanceUpdate) check() error {
	if v, ok := _u.mutation.DispatchState(); ok {
		if err := modeldevacceptance.DispatchStateValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_state", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.dispatch_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := modeldevacceptance.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseGeneration(); ok {
		if err := modeldevacceptance.LeaseGenerationValidator(v); err != nil {
			return &ValidationError{Name: "lease_generation", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.lease_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := modeldevacceptance.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StopIntentGeneration(); ok {
		if err := modeldevacceptance.StopIntentGenerationValidator(v); err != nil {
			return &ValidationError{Name: "stop_intent_generation", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.stop_intent_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StopRequestedActor(); ok {
		if err := modeldevacceptance.StopRequestedActorValidator(v); err != nil {
			return &ValidationError{Name: "stop_requested_actor", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.stop_requested_actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseDispatchState(); ok {
		if err := modeldevacceptance.CloseDispatchStateValidator(v); err != nil {
			return &ValidationError{Name: "close_dispatch_state", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_dispatch_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseAttemptCount(); ok {
		if err := modeldevacceptance.CloseAttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "close_attempt_count", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseLeaseGeneration(); ok {
		if err := modeldevacceptance.CloseLeaseGenerationValidator(v); err != nil {
			return &ValidationError{Name: "close_lease_generation", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_lease_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseLeaseOwner(); ok {
		if err := modeldevacceptance.CloseLeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "close_lease_owner", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_lease_owner": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelDevAcceptanceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelDevAcceptanceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelDevAcceptanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modeldevacceptance.Table, modeldevacceptance.Columns, sqlgraph.NewFieldSpec(modeldevacceptance.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DispatchState(); ok {
		_spec.SetField(modeldevacceptance.FieldDispatchState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(modeldevacceptance.FieldAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(modeldevacceptance.FieldAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseGeneration(); ok {
		_spec.SetField(modeldevacceptance.FieldLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseGeneration(); ok {
		_spec.AddField(modeldevacceptance.FieldLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(modeldevacceptance.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(modeldevacceptance.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseUntil(); ok {
		_spec.SetField(modeldevacceptance.FieldLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.LeaseUntilCleared() {
		_spec.ClearField(modeldevacceptance.FieldLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(modeldevacceptance.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(modeldevacceptance.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RetryBlocked(); ok {
		_spec.SetField(modeldevacceptance.FieldRetryBlocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(modeldevacceptance.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(modeldevacceptance.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerReceiptCanonical(); ok {
		_spec.SetField(modeldevacceptance.FieldOwnerReceiptCanonical, field.TypeBytes, value)
	}
	if _u.mutation.OwnerReceiptCanonicalCleared() {
		_spec.ClearField(modeldevacceptance.FieldOwnerReceiptCanonical, field.TypeBytes)
	}
	if value, ok := _u.mutation.StopIntentGeneration(); ok {
		_spec.SetField(modeldevacceptance.FieldStopIntentGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStopIntentGeneration(); ok {
		_spec.AddField(modeldevacceptance.FieldStopIntentGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StopRequestedAt(); ok {
		_spec.SetField(modeldevacceptance.FieldStopRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.StopRequestedAtCleared() {
		_spec.ClearField(modeldevacceptance.FieldStopRequestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StopRequestedActor(); ok {
		_spec.SetField(modeldevacceptance.FieldStopRequestedActor, field.TypeString, value)
	}
	if _u.mutation.StopRequestedActorCleared() {
		_spec.ClearField(modeldevacceptance.FieldStopRequestedActor, field.TypeString)
	}
	if value, ok := _u.mutation.CloseDispatchState(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseDispatchState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CloseAttemptCount(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCloseAttemptCount(); ok {
		_spec.AddField(modeldevacceptance.FieldCloseAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CloseLeaseGeneration(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCloseLeaseGeneration(); ok {
		_spec.AddField(modeldevacceptance.FieldCloseLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CloseLeaseOwner(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.CloseLeaseOwnerCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.CloseLeaseUntil(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.CloseLeaseUntilCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CloseNextAttemptAt(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.CloseNextAttemptAtCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CloseRetryBlocked(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseRetryBlocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CloseLastErrorCode(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.CloseLastErrorCodeCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.CloseReceiptCanonical(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseReceiptCanonical, field.TypeBytes, value)
	}
	if _u.mutation.CloseReceiptCanonicalCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseReceiptCanonical, field.TypeBytes)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modeldevacceptance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelDevAcceptanceUpdateOne is the builder for updating a single ModelDevAcceptance entity.
type ModelDevAcceptanceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelDevAcceptanceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDispatchState sets the "dispatch_state" field.
func (_u *ModelDevAcceptanceUpdateOne) SetDispatchState(v modeldevacceptance.DispatchState) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetDispatchState(v)
	return _u
}

// SetNillableDispatchState sets the "dispatch_state" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableDispatchState(v *modeldevacceptance.DispatchState) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetDispatchState(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *ModelDevAcceptanceUpdateOne) SetAttemptCount(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableAttemptCount(v *int64) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *ModelDevAcceptanceUpdateOne) AddAttemptCount(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLeaseGeneration sets the "lease_generation" field.
func (_u *ModelDevAcceptanceUpdateOne) SetLeaseGeneration(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.ResetLeaseGeneration()
	_u.mutation.SetLeaseGeneration(v)
	return _u
}

// SetNillableLeaseGeneration sets the "lease_generation" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableLeaseGeneration(v *int64) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetLeaseGeneration(*v)
	}
	return _u
}

// AddLeaseGeneration adds value to the "lease_generation" field.
func (_u *ModelDevAcceptanceUpdateOne) AddLeaseGeneration(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.AddLeaseGeneration(v)
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *ModelDevAcceptanceUpdateOne) SetLeaseOwner(v string) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableLeaseOwner(v *string) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearLeaseOwner() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseUntil sets the "lease_until" field.
func (_u *ModelDevAcceptanceUpdateOne) SetLeaseUntil(v time.Time) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetLeaseUntil(v)
	return _u
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableLeaseUntil(v *time.Time) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetLeaseUntil(*v)
	}
	return _u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearLeaseUntil() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearLeaseUntil()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdateOne) SetNextAttemptAt(v time.Time) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableNextAttemptAt(v *time.Time) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearNextAttemptAt() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetRetryBlocked sets the "retry_blocked" field.
func (_u *ModelDevAcceptanceUpdateOne) SetRetryBlocked(v bool) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetRetryBlocked(v)
	return _u
}

// SetNillableRetryBlocked sets the "retry_blocked" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableRetryBlocked(v *bool) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetRetryBlocked(*v)
	}
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *ModelDevAcceptanceUpdateOne) SetLastErrorCode(v string) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableLastErrorCode(v *string) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearLastErrorCode() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetOwnerReceiptCanonical sets the "owner_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdateOne) SetOwnerReceiptCanonical(v []byte) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetOwnerReceiptCanonical(v)
	return _u
}

// ClearOwnerReceiptCanonical clears the value of the "owner_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearOwnerReceiptCanonical() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearOwnerReceiptCanonical()
	return _u
}

// SetStopIntentGeneration sets the "stop_intent_generation" field.
func (_u *ModelDevAcceptanceUpdateOne) SetStopIntentGeneration(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.ResetStopIntentGeneration()
	_u.mutation.SetStopIntentGeneration(v)
	return _u
}

// SetNillableStopIntentGeneration sets the "stop_intent_generation" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableStopIntentGeneration(v *int64) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetStopIntentGeneration(*v)
	}
	return _u
}

// AddStopIntentGeneration adds value to the "stop_intent_generation" field.
func (_u *ModelDevAcceptanceUpdateOne) AddStopIntentGeneration(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.AddStopIntentGeneration(v)
	return _u
}

// SetStopRequestedAt sets the "stop_requested_at" field.
func (_u *ModelDevAcceptanceUpdateOne) SetStopRequestedAt(v time.Time) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetStopRequestedAt(v)
	return _u
}

// SetNillableStopRequestedAt sets the "stop_requested_at" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableStopRequestedAt(v *time.Time) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetStopRequestedAt(*v)
	}
	return _u
}

// ClearStopRequestedAt clears the value of the "stop_requested_at" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearStopRequestedAt() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearStopRequestedAt()
	return _u
}

// SetStopRequestedActor sets the "stop_requested_actor" field.
func (_u *ModelDevAcceptanceUpdateOne) SetStopRequestedActor(v string) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetStopRequestedActor(v)
	return _u
}

// SetNillableStopRequestedActor sets the "stop_requested_actor" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableStopRequestedActor(v *string) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetStopRequestedActor(*v)
	}
	return _u
}

// ClearStopRequestedActor clears the value of the "stop_requested_actor" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearStopRequestedActor() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearStopRequestedActor()
	return _u
}

// SetCloseDispatchState sets the "close_dispatch_state" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseDispatchState(v modeldevacceptance.CloseDispatchState) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseDispatchState(v)
	return _u
}

// SetNillableCloseDispatchState sets the "close_dispatch_state" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseDispatchState(v *modeldevacceptance.CloseDispatchState) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseDispatchState(*v)
	}
	return _u
}

// SetCloseAttemptCount sets the "close_attempt_count" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseAttemptCount(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.ResetCloseAttemptCount()
	_u.mutation.SetCloseAttemptCount(v)
	return _u
}

// SetNillableCloseAttemptCount sets the "close_attempt_count" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseAttemptCount(v *int64) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseAttemptCount(*v)
	}
	return _u
}

// AddCloseAttemptCount adds value to the "close_attempt_count" field.
func (_u *ModelDevAcceptanceUpdateOne) AddCloseAttemptCount(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.AddCloseAttemptCount(v)
	return _u
}

// SetCloseLeaseGeneration sets the "close_lease_generation" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseLeaseGeneration(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.ResetCloseLeaseGeneration()
	_u.mutation.SetCloseLeaseGeneration(v)
	return _u
}

// SetNillableCloseLeaseGeneration sets the "close_lease_generation" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseLeaseGeneration(v *int64) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseLeaseGeneration(*v)
	}
	return _u
}

// AddCloseLeaseGeneration adds value to the "close_lease_generation" field.
func (_u *ModelDevAcceptanceUpdateOne) AddCloseLeaseGeneration(v int64) *ModelDevAcceptanceUpdateOne {
	_u.mutation.AddCloseLeaseGeneration(v)
	return _u
}

// SetCloseLeaseOwner sets the "close_lease_owner" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseLeaseOwner(v string) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseLeaseOwner(v)
	return _u
}

// SetNillableCloseLeaseOwner sets the "close_lease_owner" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseLeaseOwner(v *string) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseLeaseOwner(*v)
	}
	return _u
}

// ClearCloseLeaseOwner clears the value of the "close_lease_owner" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearCloseLeaseOwner() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearCloseLeaseOwner()
	return _u
}

// SetCloseLeaseUntil sets the "close_lease_until" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseLeaseUntil(v time.Time) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseLeaseUntil(v)
	return _u
}

// SetNillableCloseLeaseUntil sets the "close_lease_until" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseLeaseUntil(v *time.Time) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseLeaseUntil(*v)
	}
	return _u
}

// ClearCloseLeaseUntil clears the value of the "close_lease_until" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearCloseLeaseUntil() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearCloseLeaseUntil()
	return _u
}

// SetCloseNextAttemptAt sets the "close_next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseNextAttemptAt(v time.Time) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseNextAttemptAt(v)
	return _u
}

// SetNillableCloseNextAttemptAt sets the "close_next_attempt_at" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseNextAttemptAt(v *time.Time) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseNextAttemptAt(*v)
	}
	return _u
}

// ClearCloseNextAttemptAt clears the value of the "close_next_attempt_at" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearCloseNextAttemptAt() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearCloseNextAttemptAt()
	return _u
}

// SetCloseRetryBlocked sets the "close_retry_blocked" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseRetryBlocked(v bool) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseRetryBlocked(v)
	return _u
}

// SetNillableCloseRetryBlocked sets the "close_retry_blocked" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseRetryBlocked(v *bool) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseRetryBlocked(*v)
	}
	return _u
}

// SetCloseLastErrorCode sets the "close_last_error_code" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseLastErrorCode(v string) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseLastErrorCode(v)
	return _u
}

// SetNillableCloseLastErrorCode sets the "close_last_error_code" field if the given value is not nil.
func (_u *ModelDevAcceptanceUpdateOne) SetNillableCloseLastErrorCode(v *string) *ModelDevAcceptanceUpdateOne {
	if v != nil {
		_u.SetCloseLastErrorCode(*v)
	}
	return _u
}

// ClearCloseLastErrorCode clears the value of the "close_last_error_code" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearCloseLastErrorCode() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearCloseLastErrorCode()
	return _u
}

// SetCloseReceiptCanonical sets the "close_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdateOne) SetCloseReceiptCanonical(v []byte) *ModelDevAcceptanceUpdateOne {
	_u.mutation.SetCloseReceiptCanonical(v)
	return _u
}

// ClearCloseReceiptCanonical clears the value of the "close_receipt_canonical" field.
func (_u *ModelDevAcceptanceUpdateOne) ClearCloseReceiptCanonical() *ModelDevAcceptanceUpdateOne {
	_u.mutation.ClearCloseReceiptCanonical()
	return _u
}

// Mutation returns the ModelDevAcceptanceMutation object of the builder.
func (_u *ModelDevAcceptanceUpdateOne) Mutation() *ModelDevAcceptanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelDevAcceptanceUpdate builder.
func (_u *ModelDevAcceptanceUpdateOne) Where(ps ...predicate.ModelDevAcceptance) *ModelDevAcceptanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelDevAcceptanceUpdateOne) Select(field string, fields ...string) *ModelDevAcceptanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelDevAcceptance entity.
func (_u *ModelDevAcceptanceUpdateOne) Save(ctx context.Context) (*ModelDevAcceptance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelDevAcceptanceUpdateOne) SaveX(ctx context.Context) *ModelDevAcceptance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelDevAcceptanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelDevAcceptanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelDevAcceptanceUpdateOne) check() error {
	if v, ok := _u.mutation.DispatchState(); ok {
		if err := modeldevacceptance.DispatchStateValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_state", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.dispatch_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := modeldevacceptance.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseGeneration(); ok {
		if err := modeldevacceptance.LeaseGenerationValidator(v); err != nil {
			return &ValidationError{Name: "lease_generation", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.lease_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := modeldevacceptance.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StopIntentGeneration(); ok {
		if err := modeldevacceptance.StopIntentGenerationValidator(v); err != nil {
			return &ValidationError{Name: "stop_intent_generation", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.stop_intent_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StopRequestedActor(); ok {
		if err := modeldevacceptance.StopRequestedActorValidator(v); err != nil {
			return &ValidationError{Name: "stop_requested_actor", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.stop_requested_actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseDispatchState(); ok {
		if err := modeldevacceptance.CloseDispatchStateValidator(v); err != nil {
			return &ValidationError{Name: "close_dispatch_state", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_dispatch_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseAttemptCount(); ok {
		if err := modeldevacceptance.CloseAttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "close_attempt_count", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseLeaseGeneration(); ok {
		if err := modeldevacceptance.CloseLeaseGenerationValidator(v); err != nil {
			return &ValidationError{Name: "close_lease_generation", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_lease_generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CloseLeaseOwner(); ok {
		if err := modeldevacceptance.CloseLeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "close_lease_owner", err: fmt.Errorf(`ent: validator failed for field "ModelDevAcceptance.close_lease_owner": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelDevAcceptanceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelDevAcceptanceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelDevAcceptanceUpdateOne) sqlSave(ctx context.Context) (_node *ModelDevAcceptance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modeldevacceptance.Table, modeldevacceptance.Columns, sqlgraph.NewFieldSpec(modeldevacceptance.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelDevAcceptance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modeldevacceptance.FieldID)
		for _, f := range fields {
			if !modeldevacceptance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modeldevacceptance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DispatchState(); ok {
		_spec.SetField(modeldevacceptance.FieldDispatchState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(modeldevacceptance.FieldAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(modeldevacceptance.FieldAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseGeneration(); ok {
		_spec.SetField(modeldevacceptance.FieldLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseGeneration(); ok {
		_spec.AddField(modeldevacceptance.FieldLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(modeldevacceptance.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(modeldevacceptance.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseUntil(); ok {
		_spec.SetField(modeldevacceptance.FieldLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.LeaseUntilCleared() {
		_spec.ClearField(modeldevacceptance.FieldLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(modeldevacceptance.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(modeldevacceptance.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RetryBlocked(); ok {
		_spec.SetField(modeldevacceptance.FieldRetryBlocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(modeldevacceptance.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(modeldevacceptance.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerReceiptCanonical(); ok {
		_spec.SetField(modeldevacceptance.FieldOwnerReceiptCanonical, field.TypeBytes, value)
	}
	if _u.mutation.OwnerReceiptCanonicalCleared() {
		_spec.ClearField(modeldevacceptance.FieldOwnerReceiptCanonical, field.TypeBytes)
	}
	if value, ok := _u.mutation.StopIntentGeneration(); ok {
		_spec.SetField(modeldevacceptance.FieldStopIntentGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStopIntentGeneration(); ok {
		_spec.AddField(modeldevacceptance.FieldStopIntentGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StopRequestedAt(); ok {
		_spec.SetField(modeldevacceptance.FieldStopRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.StopRequestedAtCleared() {
		_spec.ClearField(modeldevacceptance.FieldStopRequestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StopRequestedActor(); ok {
		_spec.SetField(modeldevacceptance.FieldStopRequestedActor, field.TypeString, value)
	}
	if _u.mutation.StopRequestedActorCleared() {
		_spec.ClearField(modeldevacceptance.FieldStopRequestedActor, field.TypeString)
	}
	if value, ok := _u.mutation.CloseDispatchState(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseDispatchState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CloseAttemptCount(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCloseAttemptCount(); ok {
		_spec.AddField(modeldevacceptance.FieldCloseAttemptCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CloseLeaseGeneration(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCloseLeaseGeneration(); ok {
		_spec.AddField(modeldevacceptance.FieldCloseLeaseGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CloseLeaseOwner(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.CloseLeaseOwnerCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.CloseLeaseUntil(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.CloseLeaseUntilCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CloseNextAttemptAt(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.CloseNextAttemptAtCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CloseRetryBlocked(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseRetryBlocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CloseLastErrorCode(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.CloseLastErrorCodeCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.CloseReceiptCanonical(); ok {
		_spec.SetField(modeldevacceptance.FieldCloseReceiptCanonical, field.TypeBytes, value)
	}
	if _u.mutation.CloseReceiptCanonicalCleared() {
		_spec.ClearField(modeldevacceptance.FieldCloseReceiptCanonical, field.TypeBytes)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ModelDevAcceptance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modeldevacceptance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
