// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/orgunit"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrgUnitCreate is the builder for creating a OrgUnit entity.
type OrgUnitCreate struct {
	config
	mutation *OrgUnitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgUnitCreate) SetCreatedAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableCreatedAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgUnitCreate) SetUpdatedAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableUpdatedAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrgUnitCreate) SetDeletedAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableDeletedAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *OrgUnitCreate) SetCreatedBy(v uint32) *OrgUnitCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableCreatedBy(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *OrgUnitCreate) SetUpdatedBy(v uint32) *OrgUnitCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableUpdatedBy(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *OrgUnitCreate) SetDeletedBy(v uint32) *OrgUnitCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableDeletedBy(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrgUnitCreate) SetStatus(v orgunit.Status) *OrgUnitCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableStatus(v *orgunit.Status) *OrgUnitCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *OrgUnitCreate) SetSortOrder(v uint32) *OrgUnitCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableSortOrder(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *OrgUnitCreate) SetTenantID(v uint32) *OrgUnitCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableTenantID(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *OrgUnitCreate) SetRemark(v string) *OrgUnitCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableRemark(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *OrgUnitCreate) SetDescription(v string) *OrgUnitCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableDescription(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *OrgUnitCreate) SetParentID(v uint32) *OrgUnitCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableParentID(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *OrgUnitCreate) SetPath(v string) *OrgUnitCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillablePath(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OrgUnitCreate) SetName(v string) *OrgUnitCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *OrgUnitCreate) SetCode(v string) *OrgUnitCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableCode(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetLeaderID sets the "leader_id" field.
func (_c *OrgUnitCreate) SetLeaderID(v uint32) *OrgUnitCreate {
	_c.mutation.SetLeaderID(v)
	return _c
}

// SetNillableLeaderID sets the "leader_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableLeaderID(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetLeaderID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *OrgUnitCreate) SetType(v orgunit.Type) *OrgUnitCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableType(v *orgunit.Type) *OrgUnitCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetBusinessScopes sets the "business_scopes" field.
func (_c *OrgUnitCreate) SetBusinessScopes(v []string) *OrgUnitCreate {
	_c.mutation.SetBusinessScopes(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *OrgUnitCreate) SetExternalID(v string) *OrgUnitCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableExternalID(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetIsLegalEntity sets the "is_legal_entity" field.
func (_c *OrgUnitCreate) SetIsLegalEntity(v bool) *OrgUnitCreate {
	_c.mutation.SetIsLegalEntity(v)
	return _c
}

// SetNillableIsLegalEntity sets the "is_legal_entity" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableIsLegalEntity(v *bool) *OrgUnitCreate {
	if v != nil {
		_c.SetIsLegalEntity(*v)
	}
	return _c
}

// SetRegistrationNumber sets the "registration_number" field.
func (_c *OrgUnitCreate) SetRegistrationNumber(v string) *OrgUnitCreate {
	_c.mutation.SetRegistrationNumber(v)
	return _c
}

// SetNillableRegistrationNumber sets the "registration_number" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableRegistrationNumber(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetRegistrationNumber(*v)
	}
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *OrgUnitCreate) SetTaxID(v string) *OrgUnitCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableTaxID(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetTaxID(*v)
	}
	return _c
}

// SetLegalEntityOrgID sets the "legal_entity_org_id" field.
func (_c *OrgUnitCreate) SetLegalEntityOrgID(v uint32) *OrgUnitCreate {
	_c.mutation.SetLegalEntityOrgID(v)
	return _c
}

// SetNillableLegalEntityOrgID sets the "legal_entity_org_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableLegalEntityOrgID(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetLegalEntityOrgID(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *OrgUnitCreate) SetAddress(v string) *OrgUnitCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableAddress(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *OrgUnitCreate) SetPhone(v string) *OrgUnitCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillablePhone(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *OrgUnitCreate) SetEmail(v string) *OrgUnitCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableEmail(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *OrgUnitCreate) SetTimezone(v string) *OrgUnitCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableTimezone(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *OrgUnitCreate) SetCountry(v string) *OrgUnitCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableCountry(v *string) *OrgUnitCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *OrgUnitCreate) SetLatitude(v float64) *OrgUnitCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableLatitude(v *float64) *OrgUnitCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *OrgUnitCreate) SetLongitude(v float64) *OrgUnitCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableLongitude(v *float64) *OrgUnitCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *OrgUnitCreate) SetStartAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableStartAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetStartAt(*v)
	}
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *OrgUnitCreate) SetEndAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableEndAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetEndAt(*v)
	}
	return _c
}

// SetContactUserID sets the "contact_user_id" field.
func (_c *OrgUnitCreate) SetContactUserID(v uint32) *OrgUnitCreate {
	_c.mutation.SetContactUserID(v)
	return _c
}

// SetNillableContactUserID sets the "contact_user_id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableContactUserID(v *uint32) *OrgUnitCreate {
	if v != nil {
		_c.SetContactUserID(*v)
	}
	return _c
}

// SetPermissionTags sets the "permission_tags" field.
func (_c *OrgUnitCreate) SetPermissionTags(v []string) *OrgUnitCreate {
	_c.mutation.SetPermissionTags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OrgUnitCreate) SetID(v uint32) *OrgUnitCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParent sets the "parent" edge to the OrgUnit entity.
func (_c *OrgUnitCreate) SetParent(v *OrgUnit) *OrgUnitCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the OrgUnit entity by IDs.
func (_c *OrgUnitCreate) AddChildIDs(ids ...uint32) *OrgUnitCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the OrgUnit entity.
func (_c *OrgUnitCreate) AddChildren(v ...*OrgUnit) *OrgUnitCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the OrgUnitMutation object of the builder.
func (_c *OrgUnitCreate) Mutation() *OrgUnitMutation {
	return _c.mutation
}

// Save creates the OrgUnit in the database.
func (_c *OrgUnitCreate) Save(ctx context.Context) (*OrgUnit, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgUnitCreate) SaveX(ctx context.Context) *OrgUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgUnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgUnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgUnitCreate) defaults() error {
	if _, ok := _c.mutation.Status(); !ok {
		v := orgunit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := orgunit.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := orgunit.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := orgunit.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.IsLegalEntity(); !ok {
		v := orgunit.DefaultIsLegalEntity
		_c.mutation.SetIsLegalEntity(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgUnitCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrgUnit.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := orgunit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := orgunit.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OrgUnit.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := orgunit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "OrgUnit.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := orgunit.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := orgunit.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OrgUnitCreate) sqlSave(ctx context.Context) (*OrgUnit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgUnitCreate) createSpec() (*OrgUnit, *sqlgraph.CreateSpec) {
	var (
		_node = &OrgUnit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orgunit.Table, sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orgunit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orgunit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(orgunit.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(orgunit.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(orgunit.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(orgunit.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(orgunit.FieldStatus, field.TypeEnum, value)
		_node.Status = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(orgunit.FieldSortOrder, field.TypeUint32, value)
		_node.SortOrder = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(orgunit.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(orgunit.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(orgunit.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(orgunit.FieldPath, field.TypeString, value)
		_node.Path = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(orgunit.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(orgunit.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.LeaderID(); ok {
		_spec.SetField(orgunit.FieldLeaderID, field.TypeUint32, value)
		_node.LeaderID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(orgunit.FieldType, field.TypeEnum, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.BusinessScopes(); ok {
		_spec.SetField(orgunit.FieldBusinessScopes, field.TypeJSON, value)
		_node.BusinessScopes = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(orgunit.FieldExternalID, field.TypeString, value)
		_node.ExternalID = &value
	}
	if value, ok := _c.mutation.IsLegalEntity(); ok {
		_spec.SetField(orgunit.FieldIsLegalEntity, field.TypeBool, value)
		_node.IsLegalEntity = &value
	}
	if value, ok := _c.mutation.RegistrationNumber(); ok {
		_spec.SetField(orgunit.FieldRegistrationNumber, field.TypeString, value)
		_node.RegistrationNumber = &value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(orgunit.FieldTaxID, field.TypeString, value)
		_node.TaxID = &value
	}
	if value, ok := _c.mutation.LegalEntityOrgID(); ok {
		_spec.SetField(orgunit.FieldLegalEntityOrgID, field.TypeUint32, value)
		_node.LegalEntityOrgID = &value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(orgunit.FieldAddress, field.TypeString, value)
		_node.Address = &value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(orgunit.FieldPhone, field.TypeString, value)
		_node.Phone = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(orgunit.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(orgunit.FieldTimezone, field.TypeString, value)
		_node.Timezone = &value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(orgunit.FieldCountry, field.TypeString, value)
		_node.Country = &value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(orgunit.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = &value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(orgunit.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = &value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(orgunit.FieldStartAt, field.TypeTime, value)
		_node.StartAt = &value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(orgunit.FieldEndAt, field.TypeTime, value)
		_node.EndAt = &value
	}
	if value, ok := _c.mutation.ContactUserID(); ok {
		_spec.SetField(orgunit.FieldContactUserID, field.TypeUint32, value)
		_node.ContactUserID = &value
	}
	if value, ok := _c.mutation.PermissionTags(); ok {
		_spec.SetField(orgunit.FieldPermissionTags, field.TypeJSON, value)
		_node.PermissionTags = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgunit.ParentTable,
			Columns: []string{orgunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgUnit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgUnitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgUnitCreate) OnConflict(opts ...sql.ConflictOption) *OrgUnitUpsertOne {
	_c.conflict = opts
	return &OrgUnitUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgUnit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgUnitCreate) OnConflictColumns(columns ...string) *OrgUnitUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgUnitUpsertOne{
		create: _c,
	}
}

type (
	// OrgUnitUpsertOne is the builder for "upsert"-ing
	//  one OrgUnit node.
	OrgUnitUpsertOne struct {
		create *OrgUnitCreate
	}

	// OrgUnitUpsert is the "OnConflict" setter.
	OrgUnitUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgUnitUpsert) SetUpdatedAt(v time.Time) *OrgUnitUpsert {
	u.Set(orgunit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateUpdatedAt() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrgUnitUpsert) ClearUpdatedAt() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgUnitUpsert) SetDeletedAt(v time.Time) *OrgUnitUpsert {
	u.Set(orgunit.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateDeletedAt() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgUnitUpsert) ClearDeletedAt() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *OrgUnitUpsert) SetCreatedBy(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateCreatedBy() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *OrgUnitUpsert) AddCreatedBy(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *OrgUnitUpsert) ClearCreatedBy() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *OrgUnitUpsert) SetUpdatedBy(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateUpdatedBy() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *OrgUnitUpsert) AddUpdatedBy(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *OrgUnitUpsert) ClearUpdatedBy() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *OrgUnitUpsert) SetDeletedBy(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateDeletedBy() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *OrgUnitUpsert) AddDeletedBy(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *OrgUnitUpsert) ClearDeletedBy() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldDeletedBy)
	return u
}

// SetStatus sets the "status" field.
func (u *OrgUnitUpsert) SetStatus(v orgunit.Status) *OrgUnitUpsert {
	u.Set(orgunit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateStatus() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *OrgUnitUpsert) SetSortOrder(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateSortOrder() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *OrgUnitUpsert) AddSortOrder(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldSortOrder, v)
	return u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *OrgUnitUpsert) ClearSortOrder() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldSortOrder)
	return u
}

// SetRemark sets the "remark" field.
func (u *OrgUnitUpsert) SetRemark(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateRemark() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *OrgUnitUpsert) ClearRemark() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldRemark)
	return u
}

// SetDescription sets the "description" field.
func (u *OrgUnitUpsert) SetDescription(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateDescription() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *OrgUnitUpsert) ClearDescription() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldDescription)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *OrgUnitUpsert) SetParentID(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateParentID() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *OrgUnitUpsert) ClearParentID() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldParentID)
	return u
}

// SetPath sets the "path" field.
func (u *OrgUnitUpsert) SetPath(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdatePath() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *OrgUnitUpsert) ClearPath() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldPath)
	return u
}

// SetName sets the "name" field.
func (u *OrgUnitUpsert) SetName(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateName() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *OrgUnitUpsert) SetCode(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateCode() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *OrgUnitUpsert) ClearCode() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldCode)
	return u
}

// SetLeaderID sets the "leader_id" field.
func (u *OrgUnitUpsert) SetLeaderID(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldLeaderID, v)
	return u
}

// UpdateLeaderID sets the "leader_id" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateLeaderID() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldLeaderID)
	return u
}

// AddLeaderID adds v to the "leader_id" field.
func (u *OrgUnitUpsert) AddLeaderID(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldLeaderID, v)
	return u
}

// ClearLeaderID clears the value of the "leader_id" field.
func (u *OrgUnitUpsert) ClearLeaderID() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldLeaderID)
	return u
}

// SetType sets the "type" field.
func (u *OrgUnitUpsert) SetType(v orgunit.Type) *OrgUnitUpsert {
	u.Set(orgunit.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateType() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldType)
	return u
}

// SetBusinessScopes sets the "business_scopes" field.
func (u *OrgUnitUpsert) SetBusinessScopes(v []string) *OrgUnitUpsert {
	u.Set(orgunit.FieldBusinessScopes, v)
	return u
}

// UpdateBusinessScopes sets the "business_scopes" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateBusinessScopes() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldBusinessScopes)
	return u
}

// ClearBusinessScopes clears the value of the "business_scopes" field.
func (u *OrgUnitUpsert) ClearBusinessScopes() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldBusinessScopes)
	return u
}

// SetExternalID sets the "external_id" field.
func (u *OrgUnitUpsert) SetExternalID(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldExternalID, v)
	return u
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateExternalID() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldExternalID)
	return u
}

// ClearExternalID clears the value of the "external_id" field.
func (u *OrgUnitUpsert) ClearExternalID() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldExternalID)
	return u
}

// SetIsLegalEntity sets the "is_legal_entity" field.
func (u *OrgUnitUpsert) SetIsLegalEntity(v bool) *OrgUnitUpsert {
	u.Set(orgunit.FieldIsLegalEntity, v)
	return u
}

// UpdateIsLegalEntity sets the "is_legal_entity" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateIsLegalEntity() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldIsLegalEntity)
	return u
}

// ClearIsLegalEntity clears the value of the "is_legal_entity" field.
func (u *OrgUnitUpsert) ClearIsLegalEntity() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldIsLegalEntity)
	return u
}

// SetRegistrationNumber sets the "registration_number" field.
func (u *OrgUnitUpsert) SetRegistrationNumber(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldRegistrationNumber, v)
	return u
}

// UpdateRegistrationNumber sets the "registration_number" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateRegistrationNumber() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldRegistrationNumber)
	return u
}

// ClearRegistrationNumber clears the value of the "registration_number" field.
func (u *OrgUnitUpsert) ClearRegistrationNumber() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldRegistrationNumber)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *OrgUnitUpsert) SetTaxID(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateTaxID() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldTaxID)
	return u
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *OrgUnitUpsert) ClearTaxID() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldTaxID)
	return u
}

// SetLegalEntityOrgID sets the "legal_entity_org_id" field.
func (u *OrgUnitUpsert) SetLegalEntityOrgID(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldLegalEntityOrgID, v)
	return u
}

// UpdateLegalEntityOrgID sets the "legal_entity_org_id" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateLegalEntityOrgID() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldLegalEntityOrgID)
	return u
}

// AddLegalEntityOrgID adds v to the "legal_entity_org_id" field.
func (u *OrgUnitUpsert) AddLegalEntityOrgID(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldLegalEntityOrgID, v)
	return u
}

// ClearLegalEntityOrgID clears the value of the "legal_entity_org_id" field.
func (u *OrgUnitUpsert) ClearLegalEntityOrgID() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldLegalEntityOrgID)
	return u
}

// SetAddress sets the "address" field.
func (u *OrgUnitUpsert) SetAddress(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateAddress() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldAddress)
	return u
}

// ClearAddress clears the value of the "address" field.
func (u *OrgUnitUpsert) ClearAddress() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldAddress)
	return u
}

// SetPhone sets the "phone" field.
func (u *OrgUnitUpsert) SetPhone(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdatePhone() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldPhone)
	return u
}

// ClearPhone clears the value of the "phone" field.
func (u *OrgUnitUpsert) ClearPhone() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldPhone)
	return u
}

// SetEmail sets the "email" field.
func (u *OrgUnitUpsert) SetEmail(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateEmail() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *OrgUnitUpsert) ClearEmail() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldEmail)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *OrgUnitUpsert) SetTimezone(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateTimezone() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldTimezone)
	return u
}

// ClearTimezone clears the value of the "timezone" field.
func (u *OrgUnitUpsert) ClearTimezone() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldTimezone)
	return u
}

// SetCountry sets the "country" field.
func (u *OrgUnitUpsert) SetCountry(v string) *OrgUnitUpsert {
	u.Set(orgunit.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateCountry() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldCountry)
	return u
}

// ClearCountry clears the value of the "country" field.
func (u *OrgUnitUpsert) ClearCountry() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldCountry)
	return u
}

// SetLatitude sets the "latitude" field.
func (u *OrgUnitUpsert) SetLatitude(v float64) *OrgUnitUpsert {
	u.Set(orgunit.FieldLatitude, v)
	return u
}

// UpdateLatitude sets the "latitude" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateLatitude() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldLatitude)
	return u
}

// AddLatitude adds v to the "latitude" field.
func (u *OrgUnitUpsert) AddLatitude(v float64) *OrgUnitUpsert {
	u.Add(orgunit.FieldLatitude, v)
	return u
}

// ClearLatitude clears the value of the "latitude" field.
func (u *OrgUnitUpsert) ClearLatitude() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldLatitude)
	return u
}

// SetLongitude sets the "longitude" field.
func (u *OrgUnitUpsert) SetLongitude(v float64) *OrgUnitUpsert {
	u.Set(orgunit.FieldLongitude, v)
	return u
}

// UpdateLongitude sets the "longitude" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateLongitude() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldLongitude)
	return u
}

// AddLongitude adds v to the "longitude" field.
func (u *OrgUnitUpsert) AddLongitude(v float64) *OrgUnitUpsert {
	u.Add(orgunit.FieldLongitude, v)
	return u
}

// ClearLongitude clears the value of the "longitude" field.
func (u *OrgUnitUpsert) ClearLongitude() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldLongitude)
	return u
}

// SetStartAt sets the "start_at" field.
func (u *OrgUnitUpsert) SetStartAt(v time.Time) *OrgUnitUpsert {
	u.Set(orgunit.FieldStartAt, v)
	return u
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateStartAt() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldStartAt)
	return u
}

// ClearStartAt clears the value of the "start_at" field.
func (u *OrgUnitUpsert) ClearStartAt() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldStartAt)
	return u
}

// SetEndAt sets the "end_at" field.
func (u *OrgUnitUpsert) SetEndAt(v time.Time) *OrgUnitUpsert {
	u.Set(orgunit.FieldEndAt, v)
	return u
}

// UpdateEndAt sets the "end_at" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateEndAt() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldEndAt)
	return u
}

// ClearEndAt clears the value of the "end_at" field.
func (u *OrgUnitUpsert) ClearEndAt() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldEndAt)
	return u
}

// SetContactUserID sets the "contact_user_id" field.
func (u *OrgUnitUpsert) SetContactUserID(v uint32) *OrgUnitUpsert {
	u.Set(orgunit.FieldContactUserID, v)
	return u
}

// UpdateContactUserID sets the "contact_user_id" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdateContactUserID() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldContactUserID)
	return u
}

// AddContactUserID adds v to the "contact_user_id" field.
func (u *OrgUnitUpsert) AddContactUserID(v uint32) *OrgUnitUpsert {
	u.Add(orgunit.FieldContactUserID, v)
	return u
}

// ClearContactUserID clears the value of the "contact_user_id" field.
func (u *OrgUnitUpsert) ClearContactUserID() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldContactUserID)
	return u
}

// SetPermissionTags sets the "permission_tags" field.
func (u *OrgUnitUpsert) SetPermissionTags(v []string) *OrgUnitUpsert {
	u.Set(orgunit.FieldPermissionTags, v)
	return u
}

// UpdatePermissionTags sets the "permission_tags" field to the value that was provided on create.
func (u *OrgUnitUpsert) UpdatePermissionTags() *OrgUnitUpsert {
	u.SetExcluded(orgunit.FieldPermissionTags)
	return u
}

// ClearPermissionTags clears the value of the "permission_tags" field.
func (u *OrgUnitUpsert) ClearPermissionTags() *OrgUnitUpsert {
	u.SetNull(orgunit.FieldPermissionTags)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OrgUnit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(orgunit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrgUnitUpsertOne) UpdateNewValues() *OrgUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(orgunit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(orgunit.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(orgunit.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgUnit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrgUnitUpsertOne) Ignore() *OrgUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgUnitUpsertOne) DoNothing() *OrgUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgUnitCreate.OnConflict
// documentation for more info.
func (u *OrgUnitUpsertOne) Update(set func(*OrgUnitUpsert)) *OrgUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgUnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgUnitUpsertOne) SetUpdatedAt(v time.Time) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateUpdatedAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrgUnitUpsertOne) ClearUpdatedAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgUnitUpsertOne) SetDeletedAt(v time.Time) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateDeletedAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgUnitUpsertOne) ClearDeletedAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *OrgUnitUpsertOne) SetCreatedBy(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *OrgUnitUpsertOne) AddCreatedBy(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateCreatedBy() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *OrgUnitUpsertOne) ClearCreatedBy() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *OrgUnitUpsertOne) SetUpdatedBy(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *OrgUnitUpsertOne) AddUpdatedBy(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateUpdatedBy() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *OrgUnitUpsertOne) ClearUpdatedBy() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *OrgUnitUpsertOne) SetDeletedBy(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *OrgUnitUpsertOne) AddDeletedBy(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateDeletedBy() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *OrgUnitUpsertOne) ClearDeletedBy() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearDeletedBy()
	})
}

// SetStatus sets the "status" field.
func (u *OrgUnitUpsertOne) SetStatus(v orgunit.Status) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateStatus() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *OrgUnitUpsertOne) SetSortOrder(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *OrgUnitUpsertOne) AddSortOrder(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateSortOrder() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *OrgUnitUpsertOne) ClearSortOrder() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearSortOrder()
	})
}

// SetRemark sets the "remark" field.
func (u *OrgUnitUpsertOne) SetRemark(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateRemark() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *OrgUnitUpsertOne) ClearRemark() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearRemark()
	})
}

// SetDescription sets the "description" field.
func (u *OrgUnitUpsertOne) SetDescription(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateDescription() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *OrgUnitUpsertOne) ClearDescription() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearDescription()
	})
}

// SetParentID sets the "parent_id" field.
func (u *OrgUnitUpsertOne) SetParentID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateParentID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *OrgUnitUpsertOne) ClearParentID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearParentID()
	})
}

// SetPath sets the "path" field.
func (u *OrgUnitUpsertOne) SetPath(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdatePath() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *OrgUnitUpsertOne) ClearPath() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearPath()
	})
}

// SetName sets the "name" field.
func (u *OrgUnitUpsertOne) SetName(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateName() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *OrgUnitUpsertOne) SetCode(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateCode() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *OrgUnitUpsertOne) ClearCode() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearCode()
	})
}

// SetLeaderID sets the "leader_id" field.
func (u *OrgUnitUpsertOne) SetLeaderID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLeaderID(v)
	})
}

// AddLeaderID adds v to the "leader_id" field.
func (u *OrgUnitUpsertOne) AddLeaderID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLeaderID(v)
	})
}

// UpdateLeaderID sets the "leader_id" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateLeaderID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLeaderID()
	})
}

// ClearLeaderID clears the value of the "leader_id" field.
func (u *OrgUnitUpsertOne) ClearLeaderID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLeaderID()
	})
}

// SetType sets the "type" field.
func (u *OrgUnitUpsertOne) SetType(v orgunit.Type) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateType() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateType()
	})
}

// SetBusinessScopes sets the "business_scopes" field.
func (u *OrgUnitUpsertOne) SetBusinessScopes(v []string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetBusinessScopes(v)
	})
}

// UpdateBusinessScopes sets the "business_scopes" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateBusinessScopes() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateBusinessScopes()
	})
}

// ClearBusinessScopes clears the value of the "business_scopes" field.
func (u *OrgUnitUpsertOne) ClearBusinessScopes() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearBusinessScopes()
	})
}

// SetExternalID sets the "external_id" field.
func (u *OrgUnitUpsertOne) SetExternalID(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateExternalID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *OrgUnitUpsertOne) ClearExternalID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearExternalID()
	})
}

// SetIsLegalEntity sets the "is_legal_entity" field.
func (u *OrgUnitUpsertOne) SetIsLegalEntity(v bool) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetIsLegalEntity(v)
	})
}

// UpdateIsLegalEntity sets the "is_legal_entity" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateIsLegalEntity() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateIsLegalEntity()
	})
}

// ClearIsLegalEntity clears the value of the "is_legal_entity" field.
func (u *OrgUnitUpsertOne) ClearIsLegalEntity() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearIsLegalEntity()
	})
}

// SetRegistrationNumber sets the "registration_number" field.
func (u *OrgUnitUpsertOne) SetRegistrationNumber(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetRegistrationNumber(v)
	})
}

// UpdateRegistrationNumber sets the "registration_number" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateRegistrationNumber() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateRegistrationNumber()
	})
}

// ClearRegistrationNumber clears the value of the "registration_number" field.
func (u *OrgUnitUpsertOne) ClearRegistrationNumber() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearRegistrationNumber()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *OrgUnitUpsertOne) SetTaxID(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateTaxID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *OrgUnitUpsertOne) ClearTaxID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearTaxID()
	})
}

// SetLegalEntityOrgID sets the "legal_entity_org_id" field.
func (u *OrgUnitUpsertOne) SetLegalEntityOrgID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLegalEntityOrgID(v)
	})
}

// AddLegalEntityOrgID adds v to the "legal_entity_org_id" field.
func (u *OrgUnitUpsertOne) AddLegalEntityOrgID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLegalEntityOrgID(v)
	})
}

// UpdateLegalEntityOrgID sets the "legal_entity_org_id" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateLegalEntityOrgID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLegalEntityOrgID()
	})
}

// ClearLegalEntityOrgID clears the value of the "legal_entity_org_id" field.
func (u *OrgUnitUpsertOne) ClearLegalEntityOrgID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLegalEntityOrgID()
	})
}

// SetAddress sets the "address" field.
func (u *OrgUnitUpsertOne) SetAddress(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateAddress() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateAddress()
	})
}

// ClearAddress clears the value of the "address" field.
func (u *OrgUnitUpsertOne) ClearAddress() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearAddress()
	})
}

// SetPhone sets the "phone" field.
func (u *OrgUnitUpsertOne) SetPhone(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdatePhone() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *OrgUnitUpsertOne) ClearPhone() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearPhone()
	})
}

// SetEmail sets the "email" field.
func (u *OrgUnitUpsertOne) SetEmail(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateEmail() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *OrgUnitUpsertOne) ClearEmail() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearEmail()
	})
}

// SetTimezone sets the "timezone" field.
func (u *OrgUnitUpsertOne) SetTimezone(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateTimezone() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateTimezone()
	})
}

// ClearTimezone clears the value of the "timezone" field.
func (u *OrgUnitUpsertOne) ClearTimezone() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearTimezone()
	})
}

// SetCountry sets the "country" field.
func (u *OrgUnitUpsertOne) SetCountry(v string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateCountry() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *OrgUnitUpsertOne) ClearCountry() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearCountry()
	})
}

// SetLatitude sets the "latitude" field.
func (u *OrgUnitUpsertOne) SetLatitude(v float64) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLatitude(v)
	})
}

// AddLatitude adds v to the "latitude" field.
func (u *OrgUnitUpsertOne) AddLatitude(v float64) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLatitude(v)
	})
}

// UpdateLatitude sets the "latitude" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateLatitude() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLatitude()
	})
}

// ClearLatitude clears the value of the "latitude" field.
func (u *OrgUnitUpsertOne) ClearLatitude() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLatitude()
	})
}

// SetLongitude sets the "longitude" field.
func (u *OrgUnitUpsertOne) SetLongitude(v float64) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLongitude(v)
	})
}

// AddLongitude adds v to the "longitude" field.
func (u *OrgUnitUpsertOne) AddLongitude(v float64) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLongitude(v)
	})
}

// UpdateLongitude sets the "longitude" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateLongitude() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLongitude()
	})
}

// ClearLongitude clears the value of the "longitude" field.
func (u *OrgUnitUpsertOne) ClearLongitude() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLongitude()
	})
}

// SetStartAt sets the "start_at" field.
func (u *OrgUnitUpsertOne) SetStartAt(v time.Time) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetStartAt(v)
	})
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateStartAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateStartAt()
	})
}

// ClearStartAt clears the value of the "start_at" field.
func (u *OrgUnitUpsertOne) ClearStartAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearStartAt()
	})
}

// SetEndAt sets the "end_at" field.
func (u *OrgUnitUpsertOne) SetEndAt(v time.Time) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetEndAt(v)
	})
}

// UpdateEndAt sets the "end_at" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateEndAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateEndAt()
	})
}

// ClearEndAt clears the value of the "end_at" field.
func (u *OrgUnitUpsertOne) ClearEndAt() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearEndAt()
	})
}

// SetContactUserID sets the "contact_user_id" field.
func (u *OrgUnitUpsertOne) SetContactUserID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetContactUserID(v)
	})
}

// AddContactUserID adds v to the "contact_user_id" field.
func (u *OrgUnitUpsertOne) AddContactUserID(v uint32) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddContactUserID(v)
	})
}

// UpdateContactUserID sets the "contact_user_id" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdateContactUserID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateContactUserID()
	})
}

// ClearContactUserID clears the value of the "contact_user_id" field.
func (u *OrgUnitUpsertOne) ClearContactUserID() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearContactUserID()
	})
}

// SetPermissionTags sets the "permission_tags" field.
func (u *OrgUnitUpsertOne) SetPermissionTags(v []string) *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetPermissionTags(v)
	})
}

// UpdatePermissionTags sets the "permission_tags" field to the value that was provided on create.
func (u *OrgUnitUpsertOne) UpdatePermissionTags() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdatePermissionTags()
	})
}

// ClearPermissionTags clears the value of the "permission_tags" field.
func (u *OrgUnitUpsertOne) ClearPermissionTags() *OrgUnitUpsertOne {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearPermissionTags()
	})
}

// Exec executes the query.
func (u *OrgUnitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgUnitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgUnitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrgUnitUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrgUnitUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrgUnitCreateBulk is the builder for creating many OrgUnit entities in bulk.
type OrgUnitCreateBulk struct {
	config
	err      error
	builders []*OrgUnitCreate
	conflict []sql.ConflictOption
}

// Save creates the OrgUnit entities in the database.
func (_c *OrgUnitCreateBulk) Save(ctx context.Context) ([]*OrgUnit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrgUnit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgUnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgUnitCreateBulk) SaveX(ctx context.Context) []*OrgUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgUnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgUnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgUnit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgUnitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgUnitCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrgUnitUpsertBulk {
	_c.conflict = opts
	return &OrgUnitUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgUnit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgUnitCreateBulk) OnConflictColumns(columns ...string) *OrgUnitUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgUnitUpsertBulk{
		create: _c,
	}
}

// OrgUnitUpsertBulk is the builder for "upsert"-ing
// a bulk of OrgUnit nodes.
type OrgUnitUpsertBulk struct {
	create *OrgUnitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrgUnit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(orgunit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrgUnitUpsertBulk) UpdateNewValues() *OrgUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(orgunit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(orgunit.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(orgunit.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgUnit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrgUnitUpsertBulk) Ignore() *OrgUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgUnitUpsertBulk) DoNothing() *OrgUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgUnitCreateBulk.OnConflict
// documentation for more info.
func (u *OrgUnitUpsertBulk) Update(set func(*OrgUnitUpsert)) *OrgUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgUnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgUnitUpsertBulk) SetUpdatedAt(v time.Time) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateUpdatedAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrgUnitUpsertBulk) ClearUpdatedAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgUnitUpsertBulk) SetDeletedAt(v time.Time) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateDeletedAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgUnitUpsertBulk) ClearDeletedAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *OrgUnitUpsertBulk) SetCreatedBy(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *OrgUnitUpsertBulk) AddCreatedBy(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateCreatedBy() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *OrgUnitUpsertBulk) ClearCreatedBy() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *OrgUnitUpsertBulk) SetUpdatedBy(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *OrgUnitUpsertBulk) AddUpdatedBy(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateUpdatedBy() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *OrgUnitUpsertBulk) ClearUpdatedBy() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *OrgUnitUpsertBulk) SetDeletedBy(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *OrgUnitUpsertBulk) AddDeletedBy(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateDeletedBy() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *OrgUnitUpsertBulk) ClearDeletedBy() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearDeletedBy()
	})
}

// SetStatus sets the "status" field.
func (u *OrgUnitUpsertBulk) SetStatus(v orgunit.Status) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateStatus() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *OrgUnitUpsertBulk) SetSortOrder(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *OrgUnitUpsertBulk) AddSortOrder(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateSortOrder() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *OrgUnitUpsertBulk) ClearSortOrder() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearSortOrder()
	})
}

// SetRemark sets the "remark" field.
func (u *OrgUnitUpsertBulk) SetRemark(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateRemark() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *OrgUnitUpsertBulk) ClearRemark() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearRemark()
	})
}

// SetDescription sets the "description" field.
func (u *OrgUnitUpsertBulk) SetDescription(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateDescription() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *OrgUnitUpsertBulk) ClearDescription() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearDescription()
	})
}

// SetParentID sets the "parent_id" field.
func (u *OrgUnitUpsertBulk) SetParentID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateParentID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *OrgUnitUpsertBulk) ClearParentID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearParentID()
	})
}

// SetPath sets the "path" field.
func (u *OrgUnitUpsertBulk) SetPath(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdatePath() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *OrgUnitUpsertBulk) ClearPath() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearPath()
	})
}

// SetName sets the "name" field.
func (u *OrgUnitUpsertBulk) SetName(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateName() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *OrgUnitUpsertBulk) SetCode(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateCode() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *OrgUnitUpsertBulk) ClearCode() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearCode()
	})
}

// SetLeaderID sets the "leader_id" field.
func (u *OrgUnitUpsertBulk) SetLeaderID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLeaderID(v)
	})
}

// AddLeaderID adds v to the "leader_id" field.
func (u *OrgUnitUpsertBulk) AddLeaderID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLeaderID(v)
	})
}

// UpdateLeaderID sets the "leader_id" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateLeaderID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLeaderID()
	})
}

// ClearLeaderID clears the value of the "leader_id" field.
func (u *OrgUnitUpsertBulk) ClearLeaderID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLeaderID()
	})
}

// SetType sets the "type" field.
func (u *OrgUnitUpsertBulk) SetType(v orgunit.Type) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateType() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateType()
	})
}

// SetBusinessScopes sets the "business_scopes" field.
func (u *OrgUnitUpsertBulk) SetBusinessScopes(v []string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetBusinessScopes(v)
	})
}

// UpdateBusinessScopes sets the "business_scopes" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateBusinessScopes() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateBusinessScopes()
	})
}

// ClearBusinessScopes clears the value of the "business_scopes" field.
func (u *OrgUnitUpsertBulk) ClearBusinessScopes() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearBusinessScopes()
	})
}

// SetExternalID sets the "external_id" field.
func (u *OrgUnitUpsertBulk) SetExternalID(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateExternalID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *OrgUnitUpsertBulk) ClearExternalID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearExternalID()
	})
}

// SetIsLegalEntity sets the "is_legal_entity" field.
func (u *OrgUnitUpsertBulk) SetIsLegalEntity(v bool) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetIsLegalEntity(v)
	})
}

// UpdateIsLegalEntity sets the "is_legal_entity" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateIsLegalEntity() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateIsLegalEntity()
	})
}

// ClearIsLegalEntity clears the value of the "is_legal_entity" field.
func (u *OrgUnitUpsertBulk) ClearIsLegalEntity() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearIsLegalEntity()
	})
}

// SetRegistrationNumber sets the "registration_number" field.
func (u *OrgUnitUpsertBulk) SetRegistrationNumber(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetRegistrationNumber(v)
	})
}

// UpdateRegistrationNumber sets the "registration_number" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateRegistrationNumber() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateRegistrationNumber()
	})
}

// ClearRegistrationNumber clears the value of the "registration_number" field.
func (u *OrgUnitUpsertBulk) ClearRegistrationNumber() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearRegistrationNumber()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *OrgUnitUpsertBulk) SetTaxID(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateTaxID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *OrgUnitUpsertBulk) ClearTaxID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearTaxID()
	})
}

// SetLegalEntityOrgID sets the "legal_entity_org_id" field.
func (u *OrgUnitUpsertBulk) SetLegalEntityOrgID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLegalEntityOrgID(v)
	})
}

// AddLegalEntityOrgID adds v to the "legal_entity_org_id" field.
func (u *OrgUnitUpsertBulk) AddLegalEntityOrgID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLegalEntityOrgID(v)
	})
}

// UpdateLegalEntityOrgID sets the "legal_entity_org_id" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateLegalEntityOrgID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLegalEntityOrgID()
	})
}

// ClearLegalEntityOrgID clears the value of the "legal_entity_org_id" field.
func (u *OrgUnitUpsertBulk) ClearLegalEntityOrgID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLegalEntityOrgID()
	})
}

// SetAddress sets the "address" field.
func (u *OrgUnitUpsertBulk) SetAddress(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateAddress() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateAddress()
	})
}

// ClearAddress clears the value of the "address" field.
func (u *OrgUnitUpsertBulk) ClearAddress() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearAddress()
	})
}

// SetPhone sets the "phone" field.
func (u *OrgUnitUpsertBulk) SetPhone(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdatePhone() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *OrgUnitUpsertBulk) ClearPhone() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearPhone()
	})
}

// SetEmail sets the "email" field.
func (u *OrgUnitUpsertBulk) SetEmail(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateEmail() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *OrgUnitUpsertBulk) ClearEmail() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearEmail()
	})
}

// SetTimezone sets the "timezone" field.
func (u *OrgUnitUpsertBulk) SetTimezone(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateTimezone() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateTimezone()
	})
}

// ClearTimezone clears the value of the "timezone" field.
func (u *OrgUnitUpsertBulk) ClearTimezone() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearTimezone()
	})
}

// SetCountry sets the "country" field.
func (u *OrgUnitUpsertBulk) SetCountry(v string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateCountry() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *OrgUnitUpsertBulk) ClearCountry() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearCountry()
	})
}

// SetLatitude sets the "latitude" field.
func (u *OrgUnitUpsertBulk) SetLatitude(v float64) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLatitude(v)
	})
}

// AddLatitude adds v to the "latitude" field.
func (u *OrgUnitUpsertBulk) AddLatitude(v float64) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLatitude(v)
	})
}

// UpdateLatitude sets the "latitude" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateLatitude() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLatitude()
	})
}

// ClearLatitude clears the value of the "latitude" field.
func (u *OrgUnitUpsertBulk) ClearLatitude() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLatitude()
	})
}

// SetLongitude sets the "longitude" field.
func (u *OrgUnitUpsertBulk) SetLongitude(v float64) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetLongitude(v)
	})
}

// AddLongitude adds v to the "longitude" field.
func (u *OrgUnitUpsertBulk) AddLongitude(v float64) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddLongitude(v)
	})
}

// UpdateLongitude sets the "longitude" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateLongitude() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateLongitude()
	})
}

// ClearLongitude clears the value of the "longitude" field.
func (u *OrgUnitUpsertBulk) ClearLongitude() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearLongitude()
	})
}

// SetStartAt sets the "start_at" field.
func (u *OrgUnitUpsertBulk) SetStartAt(v time.Time) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetStartAt(v)
	})
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateStartAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateStartAt()
	})
}

// ClearStartAt clears the value of the "start_at" field.
func (u *OrgUnitUpsertBulk) ClearStartAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearStartAt()
	})
}

// SetEndAt sets the "end_at" field.
func (u *OrgUnitUpsertBulk) SetEndAt(v time.Time) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetEndAt(v)
	})
}

// UpdateEndAt sets the "end_at" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateEndAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateEndAt()
	})
}

// ClearEndAt clears the value of the "end_at" field.
func (u *OrgUnitUpsertBulk) ClearEndAt() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearEndAt()
	})
}

// SetContactUserID sets the "contact_user_id" field.
func (u *OrgUnitUpsertBulk) SetContactUserID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetContactUserID(v)
	})
}

// AddContactUserID adds v to the "contact_user_id" field.
func (u *OrgUnitUpsertBulk) AddContactUserID(v uint32) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.AddContactUserID(v)
	})
}

// UpdateContactUserID sets the "contact_user_id" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdateContactUserID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdateContactUserID()
	})
}

// ClearContactUserID clears the value of the "contact_user_id" field.
func (u *OrgUnitUpsertBulk) ClearContactUserID() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearContactUserID()
	})
}

// SetPermissionTags sets the "permission_tags" field.
func (u *OrgUnitUpsertBulk) SetPermissionTags(v []string) *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.SetPermissionTags(v)
	})
}

// UpdatePermissionTags sets the "permission_tags" field to the value that was provided on create.
func (u *OrgUnitUpsertBulk) UpdatePermissionTags() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.UpdatePermissionTags()
	})
}

// ClearPermissionTags clears the value of the "permission_tags" field.
func (u *OrgUnitUpsertBulk) ClearPermissionTags() *OrgUnitUpsertBulk {
	return u.Update(func(s *OrgUnitUpsert) {
		s.ClearPermissionTags()
	})
}

// Exec executes the query.
func (u *OrgUnitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrgUnitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgUnitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgUnitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
