// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-admin/app/admin/service/internal/data/ent/permissionauditlog"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermissionAuditLogDelete is the builder for deleting a PermissionAuditLog entity.
type PermissionAuditLogDelete struct {
	config
	hooks    []Hook
	mutation *PermissionAuditLogMutation
}

// Where appends a list predicates to the PermissionAuditLogDelete builder.
func (_d *PermissionAuditLogDelete) Where(ps ...predicate.PermissionAuditLog) *PermissionAuditLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PermissionAuditLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionAuditLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PermissionAuditLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(permissionauditlog.Table, sqlgraph.NewFieldSpec(permissionauditlog.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PermissionAuditLogDeleteOne is the builder for deleting a single PermissionAuditLog entity.
type PermissionAuditLogDeleteOne struct {
	_d *PermissionAuditLogDelete
}

// Where appends a list predicates to the PermissionAuditLogDelete builder.
func (_d *PermissionAuditLogDeleteOne) Where(ps ...predicate.PermissionAuditLog) *PermissionAuditLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PermissionAuditLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{permissionauditlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionAuditLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
