// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/quotaoperation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuotaOperationCreate is the builder for creating a QuotaOperation entity.
type QuotaOperationCreate struct {
	config
	mutation *QuotaOperationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuotaOperationCreate) SetCreatedAt(v time.Time) *QuotaOperationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableCreatedAt(v *time.Time) *QuotaOperationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuotaOperationCreate) SetUpdatedAt(v time.Time) *QuotaOperationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableUpdatedAt(v *time.Time) *QuotaOperationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *QuotaOperationCreate) SetDeletedAt(v time.Time) *QuotaOperationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableDeletedAt(v *time.Time) *QuotaOperationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *QuotaOperationCreate) SetTenantID(v uint32) *QuotaOperationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableTenantID(v *uint32) *QuotaOperationCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetOperationID sets the "operation_id" field.
func (_c *QuotaOperationCreate) SetOperationID(v string) *QuotaOperationCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetResourceTenantID sets the "resource_tenant_id" field.
func (_c *QuotaOperationCreate) SetResourceTenantID(v string) *QuotaOperationCreate {
	_c.mutation.SetResourceTenantID(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *QuotaOperationCreate) SetResourceID(v string) *QuotaOperationCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetCreateOperationID sets the "create_operation_id" field.
func (_c *QuotaOperationCreate) SetCreateOperationID(v string) *QuotaOperationCreate {
	_c.mutation.SetCreateOperationID(v)
	return _c
}

// SetNillableCreateOperationID sets the "create_operation_id" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableCreateOperationID(v *string) *QuotaOperationCreate {
	if v != nil {
		_c.SetCreateOperationID(*v)
	}
	return _c
}

// SetActorType sets the "actor_type" field.
func (_c *QuotaOperationCreate) SetActorType(v string) *QuotaOperationCreate {
	_c.mutation.SetActorType(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *QuotaOperationCreate) SetActorID(v string) *QuotaOperationCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetOwnerService sets the "owner_service" field.
func (_c *QuotaOperationCreate) SetOwnerService(v string) *QuotaOperationCreate {
	_c.mutation.SetOwnerService(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *QuotaOperationCreate) SetAction(v string) *QuotaOperationCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *QuotaOperationCreate) SetIdempotencyKey(v string) *QuotaOperationCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *QuotaOperationCreate) SetRequestHash(v string) *QuotaOperationCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetCanonicalRequest sets the "canonical_request" field.
func (_c *QuotaOperationCreate) SetCanonicalRequest(v string) *QuotaOperationCreate {
	_c.mutation.SetCanonicalRequest(v)
	return _c
}

// SetDispatchState sets the "dispatch_state" field.
func (_c *QuotaOperationCreate) SetDispatchState(v quotaoperation.DispatchState) *QuotaOperationCreate {
	_c.mutation.SetDispatchState(v)
	return _c
}

// SetNillableDispatchState sets the "dispatch_state" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableDispatchState(v *quotaoperation.DispatchState) *QuotaOperationCreate {
	if v != nil {
		_c.SetDispatchState(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *QuotaOperationCreate) SetAttemptCount(v int) *QuotaOperationCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableAttemptCount(v *int) *QuotaOperationCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetLeaseGeneration sets the "lease_generation" field.
func (_c *QuotaOperationCreate) SetLeaseGeneration(v int64) *QuotaOperationCreate {
	_c.mutation.SetLeaseGeneration(v)
	return _c
}

// SetNillableLeaseGeneration sets the "lease_generation" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableLeaseGeneration(v *int64) *QuotaOperationCreate {
	if v != nil {
		_c.SetLeaseGeneration(*v)
	}
	return _c
}

// SetRetryBlocked sets the "retry_blocked" field.
func (_c *QuotaOperationCreate) SetRetryBlocked(v bool) *QuotaOperationCreate {
	_c.mutation.SetRetryBlocked(v)
	return _c
}

// SetNillableRetryBlocked sets the "retry_blocked" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableRetryBlocked(v *bool) *QuotaOperationCreate {
	if v != nil {
		_c.SetRetryBlocked(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *QuotaOperationCreate) SetLastErrorCode(v string) *QuotaOperationCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableLastErrorCode(v *string) *QuotaOperationCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *QuotaOperationCreate) SetNextAttemptAt(v time.Time) *QuotaOperationCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableNextAttemptAt(v *time.Time) *QuotaOperationCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLeaseOwner sets the "lease_owner" field.
func (_c *QuotaOperationCreate) SetLeaseOwner(v string) *QuotaOperationCreate {
	_c.mutation.SetLeaseOwner(v)
	return _c
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableLeaseOwner(v *string) *QuotaOperationCreate {
	if v != nil {
		_c.SetLeaseOwner(*v)
	}
	return _c
}

// SetLeaseUntil sets the "lease_until" field.
func (_c *QuotaOperationCreate) SetLeaseUntil(v time.Time) *QuotaOperationCreate {
	_c.mutation.SetLeaseUntil(v)
	return _c
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableLeaseUntil(v *time.Time) *QuotaOperationCreate {
	if v != nil {
		_c.SetLeaseUntil(*v)
	}
	return _c
}

// SetAckJSON sets the "ack_json" field.
func (_c *QuotaOperationCreate) SetAckJSON(v string) *QuotaOperationCreate {
	_c.mutation.SetAckJSON(v)
	return _c
}

// SetNillableAckJSON sets the "ack_json" field if the given value is not nil.
func (_c *QuotaOperationCreate) SetNillableAckJSON(v *string) *QuotaOperationCreate {
	if v != nil {
		_c.SetAckJSON(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuotaOperationCreate) SetID(v uint32) *QuotaOperationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the QuotaOperationMutation object of the builder.
func (_c *QuotaOperationCreate) Mutation() *QuotaOperationMutation {
	return _c.mutation
}

// Save creates the QuotaOperation in the database.
func (_c *QuotaOperationCreate) Save(ctx context.Context) (*QuotaOperation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuotaOperationCreate) SaveX(ctx context.Context) *QuotaOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaOperationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaOperationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuotaOperationCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := quotaoperation.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.DispatchState(); !ok {
		v := quotaoperation.DefaultDispatchState
		_c.mutation.SetDispatchState(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := quotaoperation.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.LeaseGeneration(); !ok {
		v := quotaoperation.DefaultLeaseGeneration
		_c.mutation.SetLeaseGeneration(v)
	}
	if _, ok := _c.mutation.RetryBlocked(); !ok {
		v := quotaoperation.DefaultRetryBlocked
		_c.mutation.SetRetryBlocked(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuotaOperationCreate) check() error {
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "QuotaOperation.operation_id"`)}
	}
	if v, ok := _c.mutation.OperationID(); ok {
		if err := quotaoperation.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.operation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceTenantID(); !ok {
		return &ValidationError{Name: "resource_tenant_id", err: errors.New(`ent: missing required field "QuotaOperation.resource_tenant_id"`)}
	}
	if v, ok := _c.mutation.ResourceTenantID(); ok {
		if err := quotaoperation.ResourceTenantIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_tenant_id", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.resource_tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "QuotaOperation.resource_id"`)}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := quotaoperation.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.resource_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CreateOperationID(); ok {
		if err := quotaoperation.CreateOperationIDValidator(v); err != nil {
			return &ValidationError{Name: "create_operation_id", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.create_operation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorType(); !ok {
		return &ValidationError{Name: "actor_type", err: errors.New(`ent: missing required field "QuotaOperation.actor_type"`)}
	}
	if v, ok := _c.mutation.ActorType(); ok {
		if err := quotaoperation.ActorTypeValidator(v); err != nil {
			return &ValidationError{Name: "actor_type", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.actor_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "QuotaOperation.actor_id"`)}
	}
	if v, ok := _c.mutation.ActorID(); ok {
		if err := quotaoperation.ActorIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_id", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.actor_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerService(); !ok {
		return &ValidationError{Name: "owner_service", err: errors.New(`ent: missing required field "QuotaOperation.owner_service"`)}
	}
	if v, ok := _c.mutation.OwnerService(); ok {
		if err := quotaoperation.OwnerServiceValidator(v); err != nil {
			return &ValidationError{Name: "owner_service", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.owner_service": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "QuotaOperation.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := quotaoperation.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "QuotaOperation.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := quotaoperation.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "QuotaOperation.request_hash"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := quotaoperation.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.request_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CanonicalRequest(); !ok {
		return &ValidationError{Name: "canonical_request", err: errors.New(`ent: missing required field "QuotaOperation.canonical_request"`)}
	}
	if v, ok := _c.mutation.CanonicalRequest(); ok {
		if err := quotaoperation.CanonicalRequestValidator(v); err != nil {
			return &ValidationError{Name: "canonical_request", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.canonical_request": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DispatchState(); !ok {
		return &ValidationError{Name: "dispatch_state", err: errors.New(`ent: missing required field "QuotaOperation.dispatch_state"`)}
	}
	if v, ok := _c.mutation.DispatchState(); ok {
		if err := quotaoperation.DispatchStateValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_state", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.dispatch_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "QuotaOperation.attempt_count"`)}
	}
	if _, ok := _c.mutation.LeaseGeneration(); !ok {
		return &ValidationError{Name: "lease_generation", err: errors.New(`ent: missing required field "QuotaOperation.lease_generation"`)}
	}
	if _, ok := _c.mutation.RetryBlocked(); !ok {
		return &ValidationError{Name: "retry_blocked", err: errors.New(`ent: missing required field "QuotaOperation.retry_blocked"`)}
	}
	if v, ok := _c.mutation.LastErrorCode(); ok {
		if err := quotaoperation.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.last_error_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaseOwner(); ok {
		if err := quotaoperation.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.lease_owner": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := quotaoperation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "QuotaOperation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *QuotaOperationCreate) sqlSave(ctx context.Context) (*QuotaOperation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuotaOperationCreate) createSpec() (*QuotaOperation, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaOperation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quotaoperation.Table, sqlgraph.NewFieldSpec(quotaoperation.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quotaoperation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quotaoperation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(quotaoperation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(quotaoperation.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(quotaoperation.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.ResourceTenantID(); ok {
		_spec.SetField(quotaoperation.FieldResourceTenantID, field.TypeString, value)
		_node.ResourceTenantID = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(quotaoperation.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.CreateOperationID(); ok {
		_spec.SetField(quotaoperation.FieldCreateOperationID, field.TypeString, value)
		_node.CreateOperationID = &value
	}
	if value, ok := _c.mutation.ActorType(); ok {
		_spec.SetField(quotaoperation.FieldActorType, field.TypeString, value)
		_node.ActorType = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(quotaoperation.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.OwnerService(); ok {
		_spec.SetField(quotaoperation.FieldOwnerService, field.TypeString, value)
		_node.OwnerService = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(quotaoperation.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(quotaoperation.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(quotaoperation.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.CanonicalRequest(); ok {
		_spec.SetField(quotaoperation.FieldCanonicalRequest, field.TypeString, value)
		_node.CanonicalRequest = value
	}
	if value, ok := _c.mutation.DispatchState(); ok {
		_spec.SetField(quotaoperation.FieldDispatchState, field.TypeEnum, value)
		_node.DispatchState = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(quotaoperation.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.LeaseGeneration(); ok {
		_spec.SetField(quotaoperation.FieldLeaseGeneration, field.TypeInt64, value)
		_node.LeaseGeneration = value
	}
	if value, ok := _c.mutation.RetryBlocked(); ok {
		_spec.SetField(quotaoperation.FieldRetryBlocked, field.TypeBool, value)
		_node.RetryBlocked = value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(quotaoperation.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = &value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(quotaoperation.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.LeaseOwner(); ok {
		_spec.SetField(quotaoperation.FieldLeaseOwner, field.TypeString, value)
		_node.LeaseOwner = &value
	}
	if value, ok := _c.mutation.LeaseUntil(); ok {
		_spec.SetField(quotaoperation.FieldLeaseUntil, field.TypeTime, value)
		_node.LeaseUntil = &value
	}
	if value, ok := _c.mutation.AckJSON(); ok {
		_spec.SetField(quotaoperation.FieldAckJSON, field.TypeString, value)
		_node.AckJSON = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaOperation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaOperationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaOperationCreate) OnConflict(opts ...sql.ConflictOption) *QuotaOperationUpsertOne {
	_c.conflict = opts
	return &QuotaOperationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaOperationCreate) OnConflictColumns(columns ...string) *QuotaOperationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaOperationUpsertOne{
		create: _c,
	}
}

type (
	// QuotaOperationUpsertOne is the builder for "upsert"-ing
	//  one QuotaOperation node.
	QuotaOperationUpsertOne struct {
		create *QuotaOperationCreate
	}

	// QuotaOperationUpsert is the "OnConflict" setter.
	QuotaOperationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaOperationUpsert) SetUpdatedAt(v time.Time) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateUpdatedAt() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *QuotaOperationUpsert) ClearUpdatedAt() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuotaOperationUpsert) SetDeletedAt(v time.Time) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateDeletedAt() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *QuotaOperationUpsert) ClearDeletedAt() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldDeletedAt)
	return u
}

// SetDispatchState sets the "dispatch_state" field.
func (u *QuotaOperationUpsert) SetDispatchState(v quotaoperation.DispatchState) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldDispatchState, v)
	return u
}

// UpdateDispatchState sets the "dispatch_state" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateDispatchState() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldDispatchState)
	return u
}

// SetAttemptCount sets the "attempt_count" field.
func (u *QuotaOperationUpsert) SetAttemptCount(v int) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldAttemptCount, v)
	return u
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateAttemptCount() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldAttemptCount)
	return u
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *QuotaOperationUpsert) AddAttemptCount(v int) *QuotaOperationUpsert {
	u.Add(quotaoperation.FieldAttemptCount, v)
	return u
}

// SetLeaseGeneration sets the "lease_generation" field.
func (u *QuotaOperationUpsert) SetLeaseGeneration(v int64) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldLeaseGeneration, v)
	return u
}

// UpdateLeaseGeneration sets the "lease_generation" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateLeaseGeneration() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldLeaseGeneration)
	return u
}

// AddLeaseGeneration adds v to the "lease_generation" field.
func (u *QuotaOperationUpsert) AddLeaseGeneration(v int64) *QuotaOperationUpsert {
	u.Add(quotaoperation.FieldLeaseGeneration, v)
	return u
}

// SetRetryBlocked sets the "retry_blocked" field.
func (u *QuotaOperationUpsert) SetRetryBlocked(v bool) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldRetryBlocked, v)
	return u
}

// UpdateRetryBlocked sets the "retry_blocked" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateRetryBlocked() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldRetryBlocked)
	return u
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *QuotaOperationUpsert) SetLastErrorCode(v string) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldLastErrorCode, v)
	return u
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateLastErrorCode() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldLastErrorCode)
	return u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *QuotaOperationUpsert) ClearLastErrorCode() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldLastErrorCode)
	return u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *QuotaOperationUpsert) SetNextAttemptAt(v time.Time) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldNextAttemptAt, v)
	return u
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateNextAttemptAt() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldNextAttemptAt)
	return u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *QuotaOperationUpsert) ClearNextAttemptAt() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldNextAttemptAt)
	return u
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *QuotaOperationUpsert) SetLeaseOwner(v string) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldLeaseOwner, v)
	return u
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateLeaseOwner() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldLeaseOwner)
	return u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *QuotaOperationUpsert) ClearLeaseOwner() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldLeaseOwner)
	return u
}

// SetLeaseUntil sets the "lease_until" field.
func (u *QuotaOperationUpsert) SetLeaseUntil(v time.Time) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldLeaseUntil, v)
	return u
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateLeaseUntil() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldLeaseUntil)
	return u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *QuotaOperationUpsert) ClearLeaseUntil() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldLeaseUntil)
	return u
}

// SetAckJSON sets the "ack_json" field.
func (u *QuotaOperationUpsert) SetAckJSON(v string) *QuotaOperationUpsert {
	u.Set(quotaoperation.FieldAckJSON, v)
	return u
}

// UpdateAckJSON sets the "ack_json" field to the value that was provided on create.
func (u *QuotaOperationUpsert) UpdateAckJSON() *QuotaOperationUpsert {
	u.SetExcluded(quotaoperation.FieldAckJSON)
	return u
}

// ClearAckJSON clears the value of the "ack_json" field.
func (u *QuotaOperationUpsert) ClearAckJSON() *QuotaOperationUpsert {
	u.SetNull(quotaoperation.FieldAckJSON)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.QuotaOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quotaoperation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuotaOperationUpsertOne) UpdateNewValues() *QuotaOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(quotaoperation.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(quotaoperation.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(quotaoperation.FieldTenantID)
		}
		if _, exists := u.create.mutation.OperationID(); exists {
			s.SetIgnore(quotaoperation.FieldOperationID)
		}
		if _, exists := u.create.mutation.ResourceTenantID(); exists {
			s.SetIgnore(quotaoperation.FieldResourceTenantID)
		}
		if _, exists := u.create.mutation.ResourceID(); exists {
			s.SetIgnore(quotaoperation.FieldResourceID)
		}
		if _, exists := u.create.mutation.CreateOperationID(); exists {
			s.SetIgnore(quotaoperation.FieldCreateOperationID)
		}
		if _, exists := u.create.mutation.ActorType(); exists {
			s.SetIgnore(quotaoperation.FieldActorType)
		}
		if _, exists := u.create.mutation.ActorID(); exists {
			s.SetIgnore(quotaoperation.FieldActorID)
		}
		if _, exists := u.create.mutation.OwnerService(); exists {
			s.SetIgnore(quotaoperation.FieldOwnerService)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(quotaoperation.FieldAction)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(quotaoperation.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.RequestHash(); exists {
			s.SetIgnore(quotaoperation.FieldRequestHash)
		}
		if _, exists := u.create.mutation.CanonicalRequest(); exists {
			s.SetIgnore(quotaoperation.FieldCanonicalRequest)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaOperation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuotaOperationUpsertOne) Ignore() *QuotaOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaOperationUpsertOne) DoNothing() *QuotaOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaOperationCreate.OnConflict
// documentation for more info.
func (u *QuotaOperationUpsertOne) Update(set func(*QuotaOperationUpsert)) *QuotaOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaOperationUpsertOne) SetUpdatedAt(v time.Time) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateUpdatedAt() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *QuotaOperationUpsertOne) ClearUpdatedAt() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuotaOperationUpsertOne) SetDeletedAt(v time.Time) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateDeletedAt() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *QuotaOperationUpsertOne) ClearDeletedAt() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDispatchState sets the "dispatch_state" field.
func (u *QuotaOperationUpsertOne) SetDispatchState(v quotaoperation.DispatchState) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetDispatchState(v)
	})
}

// UpdateDispatchState sets the "dispatch_state" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateDispatchState() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateDispatchState()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *QuotaOperationUpsertOne) SetAttemptCount(v int) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *QuotaOperationUpsertOne) AddAttemptCount(v int) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateAttemptCount() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetLeaseGeneration sets the "lease_generation" field.
func (u *QuotaOperationUpsertOne) SetLeaseGeneration(v int64) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLeaseGeneration(v)
	})
}

// AddLeaseGeneration adds v to the "lease_generation" field.
func (u *QuotaOperationUpsertOne) AddLeaseGeneration(v int64) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.AddLeaseGeneration(v)
	})
}

// UpdateLeaseGeneration sets the "lease_generation" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateLeaseGeneration() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLeaseGeneration()
	})
}

// SetRetryBlocked sets the "retry_blocked" field.
func (u *QuotaOperationUpsertOne) SetRetryBlocked(v bool) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetRetryBlocked(v)
	})
}

// UpdateRetryBlocked sets the "retry_blocked" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateRetryBlocked() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateRetryBlocked()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *QuotaOperationUpsertOne) SetLastErrorCode(v string) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateLastErrorCode() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *QuotaOperationUpsertOne) ClearLastErrorCode() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *QuotaOperationUpsertOne) SetNextAttemptAt(v time.Time) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateNextAttemptAt() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *QuotaOperationUpsertOne) ClearNextAttemptAt() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *QuotaOperationUpsertOne) SetLeaseOwner(v string) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateLeaseOwner() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLeaseOwner()
	})
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *QuotaOperationUpsertOne) ClearLeaseOwner() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearLeaseOwner()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *QuotaOperationUpsertOne) SetLeaseUntil(v time.Time) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateLeaseUntil() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *QuotaOperationUpsertOne) ClearLeaseUntil() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearLeaseUntil()
	})
}

// SetAckJSON sets the "ack_json" field.
func (u *QuotaOperationUpsertOne) SetAckJSON(v string) *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetAckJSON(v)
	})
}

// UpdateAckJSON sets the "ack_json" field to the value that was provided on create.
func (u *QuotaOperationUpsertOne) UpdateAckJSON() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateAckJSON()
	})
}

// ClearAckJSON clears the value of the "ack_json" field.
func (u *QuotaOperationUpsertOne) ClearAckJSON() *QuotaOperationUpsertOne {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearAckJSON()
	})
}

// Exec executes the query.
func (u *QuotaOperationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaOperationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaOperationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuotaOperationUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuotaOperationUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuotaOperationCreateBulk is the builder for creating many QuotaOperation entities in bulk.
type QuotaOperationCreateBulk struct {
	config
	err      error
	builders []*QuotaOperationCreate
	conflict []sql.ConflictOption
}

// Save creates the QuotaOperation entities in the database.
func (_c *QuotaOperationCreateBulk) Save(ctx context.Context) ([]*QuotaOperation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuotaOperation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaOperationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuotaOperationCreateBulk) SaveX(ctx context.Context) []*QuotaOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaOperationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaOperationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuotaOperation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuotaOperationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *QuotaOperationCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuotaOperationUpsertBulk {
	_c.conflict = opts
	return &QuotaOperationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuotaOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuotaOperationCreateBulk) OnConflictColumns(columns ...string) *QuotaOperationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuotaOperationUpsertBulk{
		create: _c,
	}
}

// QuotaOperationUpsertBulk is the builder for "upsert"-ing
// a bulk of QuotaOperation nodes.
type QuotaOperationUpsertBulk struct {
	create *QuotaOperationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QuotaOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quotaoperation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuotaOperationUpsertBulk) UpdateNewValues() *QuotaOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(quotaoperation.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(quotaoperation.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(quotaoperation.FieldTenantID)
			}
			if _, exists := b.mutation.OperationID(); exists {
				s.SetIgnore(quotaoperation.FieldOperationID)
			}
			if _, exists := b.mutation.ResourceTenantID(); exists {
				s.SetIgnore(quotaoperation.FieldResourceTenantID)
			}
			if _, exists := b.mutation.ResourceID(); exists {
				s.SetIgnore(quotaoperation.FieldResourceID)
			}
			if _, exists := b.mutation.CreateOperationID(); exists {
				s.SetIgnore(quotaoperation.FieldCreateOperationID)
			}
			if _, exists := b.mutation.ActorType(); exists {
				s.SetIgnore(quotaoperation.FieldActorType)
			}
			if _, exists := b.mutation.ActorID(); exists {
				s.SetIgnore(quotaoperation.FieldActorID)
			}
			if _, exists := b.mutation.OwnerService(); exists {
				s.SetIgnore(quotaoperation.FieldOwnerService)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(quotaoperation.FieldAction)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(quotaoperation.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.RequestHash(); exists {
				s.SetIgnore(quotaoperation.FieldRequestHash)
			}
			if _, exists := b.mutation.CanonicalRequest(); exists {
				s.SetIgnore(quotaoperation.FieldCanonicalRequest)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuotaOperation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuotaOperationUpsertBulk) Ignore() *QuotaOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuotaOperationUpsertBulk) DoNothing() *QuotaOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuotaOperationCreateBulk.OnConflict
// documentation for more info.
func (u *QuotaOperationUpsertBulk) Update(set func(*QuotaOperationUpsert)) *QuotaOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuotaOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuotaOperationUpsertBulk) SetUpdatedAt(v time.Time) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateUpdatedAt() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *QuotaOperationUpsertBulk) ClearUpdatedAt() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *QuotaOperationUpsertBulk) SetDeletedAt(v time.Time) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateDeletedAt() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *QuotaOperationUpsertBulk) ClearDeletedAt() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDispatchState sets the "dispatch_state" field.
func (u *QuotaOperationUpsertBulk) SetDispatchState(v quotaoperation.DispatchState) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetDispatchState(v)
	})
}

// UpdateDispatchState sets the "dispatch_state" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateDispatchState() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateDispatchState()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *QuotaOperationUpsertBulk) SetAttemptCount(v int) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *QuotaOperationUpsertBulk) AddAttemptCount(v int) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateAttemptCount() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetLeaseGeneration sets the "lease_generation" field.
func (u *QuotaOperationUpsertBulk) SetLeaseGeneration(v int64) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLeaseGeneration(v)
	})
}

// AddLeaseGeneration adds v to the "lease_generation" field.
func (u *QuotaOperationUpsertBulk) AddLeaseGeneration(v int64) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.AddLeaseGeneration(v)
	})
}

// UpdateLeaseGeneration sets the "lease_generation" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateLeaseGeneration() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLeaseGeneration()
	})
}

// SetRetryBlocked sets the "retry_blocked" field.
func (u *QuotaOperationUpsertBulk) SetRetryBlocked(v bool) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetRetryBlocked(v)
	})
}

// UpdateRetryBlocked sets the "retry_blocked" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateRetryBlocked() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateRetryBlocked()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *QuotaOperationUpsertBulk) SetLastErrorCode(v string) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateLastErrorCode() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *QuotaOperationUpsertBulk) ClearLastErrorCode() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *QuotaOperationUpsertBulk) SetNextAttemptAt(v time.Time) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateNextAttemptAt() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *QuotaOperationUpsertBulk) ClearNextAttemptAt() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *QuotaOperationUpsertBulk) SetLeaseOwner(v string) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateLeaseOwner() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLeaseOwner()
	})
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *QuotaOperationUpsertBulk) ClearLeaseOwner() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearLeaseOwner()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *QuotaOperationUpsertBulk) SetLeaseUntil(v time.Time) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateLeaseUntil() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *QuotaOperationUpsertBulk) ClearLeaseUntil() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearLeaseUntil()
	})
}

// SetAckJSON sets the "ack_json" field.
func (u *QuotaOperationUpsertBulk) SetAckJSON(v string) *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.SetAckJSON(v)
	})
}

// UpdateAckJSON sets the "ack_json" field to the value that was provided on create.
func (u *QuotaOperationUpsertBulk) UpdateAckJSON() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.UpdateAckJSON()
	})
}

// ClearAckJSON clears the value of the "ack_json" field.
func (u *QuotaOperationUpsertBulk) ClearAckJSON() *QuotaOperationUpsertBulk {
	return u.Update(func(s *QuotaOperationUpsert) {
		s.ClearAckJSON()
	})
}

// Exec executes the query.
func (u *QuotaOperationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuotaOperationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuotaOperationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuotaOperationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
